use super::*;

#[derive(Debug, Serialize)]
pub(crate) struct ApiCatalog {
    pub(crate) read_endpoints: Vec<&'static str>,
    pub(crate) write_endpoints: Vec<&'static str>,
}

pub(crate) fn api_catalog() -> ApiCatalog {
    ApiCatalog {
        read_endpoints: vec![
            "/api/version",
            "/api/state",
            "/api/projects",
            "/api/tasks",
            "/api/graphs",
            "/api/flows",
            "/api/merges",
            "/api/runtimes",
            "/api/runtimes/health?project=<id|name>&task=<id>&flow=<id>&role=worker|validator",
            "/api/events",
            "/api/events/inspect?event_id=<id>",
            "/api/verify/results?attempt_id=<id>&output=true|false",
            "/api/attempts/inspect?attempt_id=<id>&diff=true|false",
            "/api/runtime-stream?attempt_id=<id>&flow_id=<id>&limit=<n>&detail=summary|observability|telemetry",
            "/api/attempts/diff?attempt_id=<id>",
            "/api/flows/replay?flow_id=<id>",
            "/api/worktrees?flow_id=<id>",
            "/api/worktrees/inspect?task_id=<id>",
            "/api/governance/constitution?project=<id|name>",
            "/api/governance/documents?project=<id|name>",
            "/api/governance/documents/inspect?project=<id|name>&document_id=<id>",
            "/api/governance/notepad?project=<id|name>",
            "/api/governance/global/notepad",
            "/api/governance/global/skills",
            "/api/governance/global/skills/inspect?skill_id=<id>",
            "/api/governance/global/templates",
            "/api/governance/global/templates/inspect?template_id=<id>",
        ],
        write_endpoints: vec![
            "/api/projects/create",
            "/api/projects/update",
            "/api/projects/delete",
            "/api/projects/runtime",
            "/api/runtime/defaults",
            "/api/projects/repos/attach",
            "/api/projects/repos/detach",
            "/api/tasks/create",
            "/api/tasks/update",
            "/api/tasks/delete",
            "/api/tasks/runtime",
            "/api/tasks/run-mode",
            "/api/tasks/close",
            "/api/tasks/start",
            "/api/tasks/complete",
            "/api/tasks/retry",
            "/api/tasks/abort",
            "/api/graphs/create",
            "/api/graphs/delete",
            "/api/graphs/dependencies/add",
            "/api/graphs/checks/add",
            "/api/graphs/validate",
            "/api/flows/create",
            "/api/flows/delete",
            "/api/flows/start",
            "/api/flows/tick",
            "/api/flows/pause",
            "/api/flows/resume",
            "/api/flows/abort",
            "/api/flows/run-mode",
            "/api/flows/dependencies/add",
            "/api/flows/runtime",
            "/api/verify/override",
            "/api/verify/run",
            "/api/merge/prepare",
            "/api/merge/approve",
            "/api/merge/execute",
            "/api/checkpoints/complete",
            "/api/worktrees/cleanup",
            "/api/governance/constitution/check",
            "/api/governance/graph-snapshot/refresh",
        ],
    }
}
