use super::*;

impl Registry {
    #[allow(clippy::too_many_lines)]
    pub(crate) fn merge_execute_via_pr(
        &self,
        flow_id: &str,
        options: MergeExecuteOptions,
    ) -> Result<crate::core::state::MergeState> {
        let origin = "registry:merge_execute_via_pr";
        let flow = self.get_flow(flow_id)?;

        let _ = self.enforce_constitution_gate(
            flow.project_id,
            "merge_execute",
            CorrelationIds::for_graph_flow(flow.project_id, flow.graph_id, flow.id),
            origin,
        )?;

        let state = self.state()?;
        let ms = state.merge_states.get(&flow.id).ok_or_else(|| {
            HivemindError::user(
                "merge_not_prepared",
                "No merge preparation exists for this flow",
                origin,
            )
        })?;

        if ms.status != crate::core::state::MergeStatus::Approved {
            return Err(HivemindError::user(
                "merge_not_approved",
                "Merge has not been approved",
                origin,
            ));
        }
        if flow.state != FlowState::FrozenForMerge {
            return Err(HivemindError::user(
                "flow_not_frozen_for_merge",
                "Flow must be frozen for merge before execution",
                origin,
            ));
        }

        let _integration_lock = self.acquire_flow_integration_lock(flow.id, origin)?;
        self.emit_integration_lock_acquired(&flow, "merge_execute_pr", origin)?;

        let managers = Self::worktree_managers_for_flow(&flow, &state, origin)?;
        if managers.len() != 1 {
            return Err(HivemindError::user(
                "pr_merge_multi_repo_unsupported",
                "PR merge mode currently supports exactly one repository",
                origin,
            ));
        }
        let (_repo_name, manager) = managers.into_iter().next().ok_or_else(|| {
            HivemindError::system(
                "repo_not_found",
                "No repository attached to project",
                origin,
            )
        })?;
        let repo_path = manager.repo_path().to_path_buf();
        let merge_branch = format!("integration/{}/prepare", flow.id);
        let merge_ref = format!("refs/heads/{merge_branch}");
        if !Self::git_ref_exists(&repo_path, &merge_ref) {
            return Err(HivemindError::user(
                "merge_branch_not_found",
                "Prepared integration branch not found",
                origin,
            )
            .with_hint("Run 'hivemind merge prepare' again"));
        }

        let target_branch = ms
            .target_branch
            .clone()
            .unwrap_or_else(|| "main".to_string());
        let old_target_head = std::process::Command::new("git")
            .current_dir(&repo_path)
            .args(["rev-parse", &target_branch])
            .output()
            .ok()
            .filter(|o| o.status.success())
            .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_string());

        let push = std::process::Command::new("git")
            .current_dir(&repo_path)
            .args(["push", "--set-upstream", "origin", &merge_branch])
            .output()
            .map_err(|e| HivemindError::system("git_push_failed", e.to_string(), origin))?;
        if !push.status.success() {
            return Err(HivemindError::git(
                "git_push_failed",
                String::from_utf8_lossy(&push.stderr).to_string(),
                origin,
            ));
        }

        let title = format!("Hivemind flow {} merge", flow.id);
        let body = format!(
            "Automated merge PR for flow {}\n\nTarget: {}\n\nGenerated by Hivemind.",
            flow.id, target_branch
        );

        let create = std::process::Command::new("gh")
            .current_dir(&repo_path)
            .args([
                "pr",
                "create",
                "--base",
                &target_branch,
                "--head",
                &merge_branch,
                "--title",
                &title,
                "--body",
                &body,
            ])
            .output()
            .map_err(|e| HivemindError::system("gh_not_available", e.to_string(), origin))?;

        if !create.status.success() {
            let list_existing = std::process::Command::new("gh")
                .current_dir(&repo_path)
                .args([
                    "pr",
                    "list",
                    "--state",
                    "open",
                    "--base",
                    &target_branch,
                    "--head",
                    &merge_branch,
                    "--json",
                    "number",
                    "--jq",
                    ".[0].number",
                ])
                .output()
                .map_err(|e| HivemindError::system("gh_pr_list_failed", e.to_string(), origin))?;

            let existing = String::from_utf8_lossy(&list_existing.stdout)
                .trim()
                .to_string();
            if existing.is_empty() {
                return Err(HivemindError::system(
                    "gh_pr_create_failed",
                    String::from_utf8_lossy(&create.stderr).to_string(),
                    origin,
                ));
            }
        }

        let pr_number_out = std::process::Command::new("gh")
            .current_dir(&repo_path)
            .args(["pr", "view", "--json", "number", "--jq", ".number"])
            .output()
            .map_err(|e| HivemindError::system("gh_pr_view_failed", e.to_string(), origin))?;
        if !pr_number_out.status.success() {
            return Err(HivemindError::system(
                "gh_pr_view_failed",
                String::from_utf8_lossy(&pr_number_out.stderr).to_string(),
                origin,
            ));
        }
        let pr_number = String::from_utf8_lossy(&pr_number_out.stdout)
            .trim()
            .to_string();
        if pr_number.is_empty() {
            return Err(HivemindError::system(
                "gh_pr_view_failed",
                "Unable to resolve PR number".to_string(),
                origin,
            ));
        }

        if options.monitor_ci {
            let checks = std::process::Command::new("gh")
                .current_dir(&repo_path)
                .args(["pr", "checks", &pr_number, "--watch", "--required"])
                .output()
                .map_err(|e| HivemindError::system("gh_pr_checks_failed", e.to_string(), origin))?;
            if !checks.status.success() {
                return Err(HivemindError::system(
                    "gh_pr_checks_failed",
                    String::from_utf8_lossy(&checks.stderr).to_string(),
                    origin,
                ));
            }
        }

        let merged_now = if options.auto_merge {
            let mut args = vec!["pr", "merge", &pr_number, "--squash", "--delete-branch"];
            if !options.monitor_ci {
                args.push("--auto");
            }
            let merge = std::process::Command::new("gh")
                .current_dir(&repo_path)
                .args(args)
                .output()
                .map_err(|e| HivemindError::system("gh_pr_merge_failed", e.to_string(), origin))?;
            if !merge.status.success() {
                return Err(HivemindError::system(
                    "gh_pr_merge_failed",
                    String::from_utf8_lossy(&merge.stderr).to_string(),
                    origin,
                ));
            }
            options.monitor_ci
        } else {
            false
        };

        if options.pull_after && merged_now {
            let checkout = std::process::Command::new("git")
                .current_dir(&repo_path)
                .args(["checkout", &target_branch])
                .output()
                .map_err(|e| HivemindError::system("git_checkout_failed", e.to_string(), origin))?;
            if !checkout.status.success() {
                return Err(HivemindError::git(
                    "git_checkout_failed",
                    String::from_utf8_lossy(&checkout.stderr).to_string(),
                    origin,
                ));
            }

            let pull = std::process::Command::new("git")
                .current_dir(&repo_path)
                .args(["pull", "--ff-only", "origin", &target_branch])
                .output()
                .map_err(|e| HivemindError::system("git_pull_failed", e.to_string(), origin))?;
            if !pull.status.success() {
                return Err(HivemindError::git(
                    "git_pull_failed",
                    String::from_utf8_lossy(&pull.stderr).to_string(),
                    origin,
                ));
            }
        }

        if merged_now {
            let new_target_head = std::process::Command::new("git")
                .current_dir(&repo_path)
                .args(["rev-parse", &target_branch])
                .output()
                .ok()
                .filter(|o| o.status.success())
                .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_string())
                .unwrap_or_default();

            let mut commits = Vec::new();
            if let Some(old_head) = old_target_head {
                let rev_list = std::process::Command::new("git")
                    .current_dir(&repo_path)
                    .args([
                        "rev-list",
                        "--reverse",
                        &format!("{old_head}..{new_target_head}"),
                    ])
                    .output()
                    .ok()
                    .filter(|o| o.status.success())
                    .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_string())
                    .unwrap_or_default();
                if !rev_list.is_empty() {
                    commits.extend(
                        rev_list
                            .lines()
                            .map(str::trim)
                            .filter(|s| !s.is_empty())
                            .map(String::from),
                    );
                }
            } else if !new_target_head.is_empty() {
                commits.push(new_target_head);
            }

            self.append_event(
                Event::new(
                    EventPayload::MergeCompleted {
                        flow_id: flow.id,
                        commits,
                    },
                    CorrelationIds::for_graph_flow(flow.project_id, flow.graph_id, flow.id),
                ),
                origin,
            )?;

            self.trigger_graph_snapshot_refresh(flow.project_id, "merge_completed", origin);
        }

        let state = self.state()?;
        state.merge_states.get(&flow.id).cloned().ok_or_else(|| {
            HivemindError::system(
                "merge_state_not_found",
                "Merge state not found after PR execution",
                origin,
            )
        })
    }
}
