//! Auto-generated registry split module: context.
//!
//! Generated by `scripts/registry_split_migrator.py`.
#![allow(clippy::wildcard_imports, unused_imports)]

use crate::core::registry::shared_prelude::*;
use crate::core::registry::shared_types::*;
use crate::core::registry::types::*;
use crate::core::registry::{
    Registry, ATTEMPT_CONTEXT_MAX_EXPAND_DEPTH, ATTEMPT_CONTEXT_SCHEMA_VERSION,
    ATTEMPT_CONTEXT_SECTION_BUDGET_BYTES, ATTEMPT_CONTEXT_TOTAL_BUDGET_BYTES,
    ATTEMPT_CONTEXT_TRUNCATION_POLICY, ATTEMPT_CONTEXT_VERSION, CONSTITUTION_SCHEMA_VERSION,
    CONSTITUTION_VERSION, GOVERNANCE_EXPORT_IMPORT_BOUNDARY, GOVERNANCE_FROM_LAYOUT,
    GOVERNANCE_PROJECTION_VERSION, GOVERNANCE_RECOVERY_SNAPSHOT_SCHEMA_VERSION,
    GOVERNANCE_SCHEMA_VERSION, GOVERNANCE_TO_LAYOUT, GRAPH_SNAPSHOT_SCHEMA_VERSION,
    GRAPH_SNAPSHOT_VERSION,
};

mod support;
mod window;

impl Registry {
    #[allow(clippy::too_many_lines, clippy::too_many_arguments)]
    pub(crate) fn assemble_attempt_context(
        &self,
        state: &AppState,
        flow: &TaskFlow,
        task_id: Uuid,
        attempt_id: Uuid,
        runtime_name: &str,
        prior_attempt_ids: &[Uuid],
        workflow_manifest: Option<AttemptContextWorkflowManifest>,
        workflow_section: Option<String>,
        origin: &'static str,
    ) -> Result<AttemptContextBuildResult> {
        let mut source_data =
            self.build_attempt_context_sources(state, flow, task_id, prior_attempt_ids, origin)?;
        source_data.workflow_manifest = workflow_manifest;
        source_data.workflow_section = workflow_section;

        let mut ordered_inputs = vec![
            "constitution".to_string(),
            "system_prompt".to_string(),
            "skills".to_string(),
            "project_documents".to_string(),
        ];
        if source_data.workflow_manifest.is_some() {
            ordered_inputs.push("workflow_step".to_string());
        }
        ordered_inputs.push("graph_summary".to_string());
        let excluded_sources = vec![
            "project_notepad".to_string(),
            "global_notepad".to_string(),
            "implicit_memory".to_string(),
        ];

        let mut per_section_budget_bytes = BTreeMap::new();
        for section in &ordered_inputs {
            per_section_budget_bytes.insert(section.clone(), ATTEMPT_CONTEXT_SECTION_BUDGET_BYTES);
        }
        let budget_policy = ContextBudgetPolicy {
            total_budget_bytes: ATTEMPT_CONTEXT_TOTAL_BUDGET_BYTES,
            default_section_budget_bytes: ATTEMPT_CONTEXT_SECTION_BUDGET_BYTES,
            per_section_budget_bytes: per_section_budget_bytes.clone(),
            max_expand_depth: ATTEMPT_CONTEXT_MAX_EXPAND_DEPTH,
            deduplicate: true,
            truncation_policy: ATTEMPT_CONTEXT_TRUNCATION_POLICY.to_string(),
        };

        let window_result = Self::build_attempt_context_window(
            attempt_id,
            runtime_name,
            &ordered_inputs,
            budget_policy,
            source_data.constitution_section,
            source_data.system_prompt_section,
            &source_data.skill_sections,
            &source_data.document_sections,
            source_data.workflow_section.clone(),
            source_data.graph_section,
            origin,
        )?;

        let manifest = AttemptContextManifest {
            schema_version: ATTEMPT_CONTEXT_SCHEMA_VERSION.to_string(),
            manifest_version: ATTEMPT_CONTEXT_VERSION,
            ordered_inputs: ordered_inputs.clone(),
            excluded_sources,
            constitution: AttemptContextConstitutionManifest {
                path: source_data.constitution_path,
                revision: source_data.constitution_revision,
                digest: source_data.constitution_digest,
                content_hash: source_data.constitution_content_hash,
            },
            template_id: source_data.template_id,
            template_event_id: source_data.template_event_id,
            template_schema_version: source_data.template_schema_version,
            template_projection_version: source_data.template_projection_version,
            system_prompt: source_data.system_prompt_manifest,
            skills: source_data.skill_manifest,
            documents: source_data.document_manifest,
            workflow: source_data.workflow_manifest,
            graph_summary: source_data.graph_summary,
            retry_links: source_data.retry_links,
            budget: AttemptContextBudgetManifest {
                total_budget_bytes: ATTEMPT_CONTEXT_TOTAL_BUDGET_BYTES,
                default_section_budget_bytes: ATTEMPT_CONTEXT_SECTION_BUDGET_BYTES,
                per_section_budget_bytes,
                max_expand_depth: ATTEMPT_CONTEXT_MAX_EXPAND_DEPTH,
                deduplicate: true,
                original_size_bytes: window_result.original_size_bytes,
                context_size_bytes: window_result.context_size_bytes,
                truncated_sections: window_result.truncated_sections.clone(),
                truncation_reasons: window_result.truncation_reasons.clone(),
                policy: ATTEMPT_CONTEXT_TRUNCATION_POLICY.to_string(),
            },
        };

        let (manifest_json, manifest_hash, inputs_hash, context_hash) =
            Self::finalize_attempt_context_manifest(
                &manifest,
                &ordered_inputs,
                &source_data.prior_manifest_hashes,
                &window_result.context_window_state_hash,
                &window_result.context,
                origin,
            )?;
        self.sync_attempt_context_graph_into_runtime_registry(
            state,
            flow,
            task_id,
            attempt_id,
            runtime_name,
            &manifest,
            &manifest_hash,
            &context_hash,
            origin,
        )?;

        Ok(AttemptContextBuildResult {
            manifest_json,
            manifest_hash,
            inputs_hash,
            context: window_result.context,
            context_hash,
            original_size_bytes: window_result.original_size_bytes,
            context_size_bytes: window_result.context_size_bytes,
            truncated_sections: window_result.truncated_sections,
            truncation_reasons: window_result.truncation_reasons,
            prior_manifest_hashes: source_data.prior_manifest_hashes,
            context_window_id: window_result.context_window_id,
            context_window_state_hash: window_result.context_window_state_hash,
            context_window_snapshot_json: window_result.context_window_snapshot_json,
            context_window_ops: window_result.context_window_ops,
            template_document_ids: source_data.template_document_ids,
            included_document_ids: source_data.included_document_ids,
            excluded_document_ids: source_data.excluded_document_ids,
            resolved_document_ids: source_data.resolved_document_ids,
        })
    }
}
