//! Auto-generated registry split module: flow.
//!
//! Generated by `scripts/registry_split_migrator.py`.
#![allow(clippy::wildcard_imports, unused_imports)]

use crate::core::registry::shared_prelude::*;
use crate::core::registry::shared_types::*;
use crate::core::registry::types::*;
use crate::core::registry::{
    Registry, ATTEMPT_CONTEXT_MAX_EXPAND_DEPTH, ATTEMPT_CONTEXT_SCHEMA_VERSION,
    ATTEMPT_CONTEXT_SECTION_BUDGET_BYTES, ATTEMPT_CONTEXT_TOTAL_BUDGET_BYTES,
    ATTEMPT_CONTEXT_TRUNCATION_POLICY, ATTEMPT_CONTEXT_VERSION, CONSTITUTION_SCHEMA_VERSION,
    CONSTITUTION_VERSION, GOVERNANCE_EXPORT_IMPORT_BOUNDARY, GOVERNANCE_FROM_LAYOUT,
    GOVERNANCE_PROJECTION_VERSION, GOVERNANCE_RECOVERY_SNAPSHOT_SCHEMA_VERSION,
    GOVERNANCE_SCHEMA_VERSION, GOVERNANCE_TO_LAYOUT, GRAPH_SNAPSHOT_SCHEMA_VERSION,
    GRAPH_SNAPSHOT_VERSION,
};

mod checkpoint;
mod execution;
mod management;
mod merge;
mod support;
mod verification;

impl Registry {
    pub fn flow_runtime_set(
        &self,
        flow_id: &str,
        role: RuntimeRole,
        adapter: &str,
        binary_path: &str,
        model: Option<String>,
        args: &[String],
        env: &[String],
        timeout_ms: u64,
        max_parallel_tasks: u16,
    ) -> Result<TaskFlow> {
        let flow = self.get_flow(flow_id)?;
        if max_parallel_tasks == 0 {
            return Err(HivemindError::user(
                "invalid_max_parallel_tasks",
                "max_parallel_tasks must be at least 1",
                "registry:flow_runtime_set",
            )
            .with_hint("Use --max-parallel-tasks 1 or higher"));
        }
        Self::ensure_supported_runtime_adapter(adapter, "registry:flow_runtime_set")?;
        let env_map = Self::parse_runtime_env_pairs(env, "registry:flow_runtime_set")?;
        self.append_event(
            Event::new(
                EventPayload::TaskFlowRuntimeConfigured {
                    flow_id: flow.id,
                    role,
                    adapter_name: adapter.to_string(),
                    binary_path: binary_path.to_string(),
                    model,
                    args: args.to_vec(),
                    env: env_map,
                    timeout_ms,
                    max_parallel_tasks,
                },
                CorrelationIds::for_graph_flow(flow.project_id, flow.graph_id, flow.id),
            ),
            "registry:flow_runtime_set",
        )?;
        self.get_flow(flow_id)
    }

    pub fn flow_runtime_clear(&self, flow_id: &str, role: RuntimeRole) -> Result<TaskFlow> {
        let flow = self.get_flow(flow_id)?;
        self.append_event(
            Event::new(
                EventPayload::TaskFlowRuntimeCleared {
                    flow_id: flow.id,
                    role,
                },
                CorrelationIds::for_graph_flow(flow.project_id, flow.graph_id, flow.id),
            ),
            "registry:flow_runtime_clear",
        )?;
        self.get_flow(flow_id)
    }

    pub fn flow_set_run_mode(&self, flow_id: &str, mode: RunMode) -> Result<TaskFlow> {
        let flow = self.get_flow(flow_id)?;
        if flow.run_mode == mode {
            return Ok(flow);
        }
        self.append_event(
            Event::new(
                EventPayload::TaskFlowRunModeSet {
                    flow_id: flow.id,
                    mode,
                },
                CorrelationIds::for_graph_flow(flow.project_id, flow.graph_id, flow.id),
            ),
            "registry:flow_set_run_mode",
        )?;
        let updated = self.get_flow(flow_id)?;
        if mode == RunMode::Auto {
            if updated.state == FlowState::Created {
                let state = self.state()?;
                if Self::unmet_flow_dependencies(&state, &updated).is_empty() {
                    return self.start_flow(flow_id);
                }
            }
            if updated.state == FlowState::Running {
                return self.auto_progress_flow(flow_id);
            }
        }
        Ok(updated)
    }

    pub fn flow_add_dependency(&self, flow_id: &str, depends_on_flow_id: &str) -> Result<TaskFlow> {
        let flow = self.get_flow(flow_id)?;
        let dependency = self.get_flow(depends_on_flow_id)?;
        if flow.id == dependency.id {
            return Err(HivemindError::user(
                "flow_dependency_self",
                "A flow cannot depend on itself",
                "registry:flow_add_dependency",
            ));
        }
        if flow.project_id != dependency.project_id {
            return Err(HivemindError::user(
                "flow_dependency_cross_project",
                "Flows must belong to the same project",
                "registry:flow_add_dependency",
            ));
        }
        if flow.state != FlowState::Created {
            return Err(HivemindError::user(
                "flow_dependency_locked",
                "Flow dependencies can only be changed while flow is in CREATED state",
                "registry:flow_add_dependency",
            ));
        }

        let state = self.state()?;
        let mut deps = flow.depends_on_flows.clone();
        deps.insert(dependency.id);

        let has_cycle = |state: &AppState, start: Uuid, deps_snapshot: &HashSet<Uuid>| {
            let mut stack: Vec<Uuid> = deps_snapshot.iter().copied().collect();
            let mut seen: HashSet<Uuid> = HashSet::new();
            while let Some(next) = stack.pop() {
                if next == start {
                    return true;
                }
                if !seen.insert(next) {
                    continue;
                }
                if let Some(other) = state.flows.get(&next) {
                    for dep in &other.depends_on_flows {
                        stack.push(*dep);
                    }
                }
            }
            false
        };
        if has_cycle(&state, flow.id, &deps) {
            return Err(HivemindError::user(
                "flow_dependency_cycle",
                "Flow dependency introduces a cycle",
                "registry:flow_add_dependency",
            ));
        }

        self.append_event(
            Event::new(
                EventPayload::TaskFlowDependencyAdded {
                    flow_id: flow.id,
                    depends_on_flow_id: dependency.id,
                },
                CorrelationIds::for_graph_flow(flow.project_id, flow.graph_id, flow.id),
            ),
            "registry:flow_add_dependency",
        )?;
        self.get_flow(flow_id)
    }
}
