//! Auto-generated registry split module: graph.
//!
//! Generated by `scripts/registry_split_migrator.py`.
#![allow(clippy::wildcard_imports, unused_imports)]

use crate::core::registry::shared_prelude::*;
use crate::core::registry::shared_types::*;
use crate::core::registry::types::*;
use crate::core::registry::{
    Registry, ATTEMPT_CONTEXT_MAX_EXPAND_DEPTH, ATTEMPT_CONTEXT_SCHEMA_VERSION,
    ATTEMPT_CONTEXT_SECTION_BUDGET_BYTES, ATTEMPT_CONTEXT_TOTAL_BUDGET_BYTES,
    ATTEMPT_CONTEXT_TRUNCATION_POLICY, ATTEMPT_CONTEXT_VERSION, CONSTITUTION_SCHEMA_VERSION,
    CONSTITUTION_VERSION, GOVERNANCE_EXPORT_IMPORT_BOUNDARY, GOVERNANCE_FROM_LAYOUT,
    GOVERNANCE_PROJECTION_VERSION, GOVERNANCE_RECOVERY_SNAPSHOT_SCHEMA_VERSION,
    GOVERNANCE_SCHEMA_VERSION, GOVERNANCE_TO_LAYOUT, GRAPH_SNAPSHOT_SCHEMA_VERSION,
    GRAPH_SNAPSHOT_VERSION,
};

mod constitution;
mod snapshot;

impl Registry {
    pub fn list_graphs(&self, project_id_or_name: Option<&str>) -> Result<Vec<TaskGraph>> {
        let project_filter = match project_id_or_name {
            Some(id_or_name) => Some(self.get_project(id_or_name)?.id),
            None => None,
        };

        let state = self.state()?;
        let mut graphs: Vec<_> = state
            .graphs
            .into_values()
            .filter(|g| project_filter.is_none_or(|pid| g.project_id == pid))
            .collect();
        graphs.sort_by(|a, b| a.updated_at.cmp(&b.updated_at));
        graphs.reverse();
        Ok(graphs)
    }

    #[allow(clippy::too_many_arguments)]
    pub(crate) fn append_graph_query_executed_event(
        &self,
        project_id: Uuid,
        flow_id: Option<Uuid>,
        task_id: Option<Uuid>,
        attempt_id: Option<Uuid>,
        source: &str,
        result: &GraphQueryResult,
        duration_ms: u64,
        correlation: CorrelationIds,
        origin: &'static str,
    ) -> Result<()> {
        self.append_event(
            Event::new(
                EventPayload::GraphQueryExecuted {
                    project_id,
                    flow_id,
                    task_id,
                    attempt_id,
                    source: source.to_string(),
                    query_kind: result.query_kind.clone(),
                    result_node_count: result.nodes.len(),
                    result_edge_count: result.edges.len(),
                    visited_node_count: result.cost.visited_nodes,
                    visited_edge_count: result.cost.visited_edges,
                    max_results: result.max_results,
                    truncated: result.truncated,
                    duration_ms,
                    canonical_fingerprint: result.canonical_fingerprint.clone(),
                },
                correlation,
            ),
            origin,
        )
    }

    #[allow(clippy::too_many_arguments)]
    pub(crate) fn append_graph_query_event_for_native_tool_call(
        &self,
        flow: &TaskFlow,
        task_id: Uuid,
        attempt_id: Uuid,
        tool_name: &str,
        response_payload: &str,
        correlation: CorrelationIds,
        origin: &'static str,
    ) -> Result<()> {
        if tool_name != "graph_query" {
            return Ok(());
        }
        let Ok(decoded) = serde_json::from_str::<serde_json::Value>(response_payload) else {
            return Ok(());
        };
        if decoded.get("ok").and_then(serde_json::Value::as_bool) != Some(true) {
            return Ok(());
        }
        let Some(output) = decoded.get("output") else {
            return Ok(());
        };
        let Ok(result) = serde_json::from_value::<GraphQueryResult>(output.clone()) else {
            return Ok(());
        };
        self.append_graph_query_executed_event(
            flow.project_id,
            Some(flow.id),
            Some(task_id),
            Some(attempt_id),
            "native_tool_graph_query",
            &result,
            result.duration_ms,
            correlation,
            origin,
        )
    }

    pub(crate) fn map_graph_query_error(
        err: crate::core::graph_query::GraphQueryError,
    ) -> HivemindError {
        let mut mapped = HivemindError::user(err.code, err.message, "registry:graph_query_execute");
        if matches!(
            mapped.code.as_str(),
            "graph_query_bounds_invalid"
                | "graph_query_bounds_exceeded"
                | "graph_query_depth_invalid"
                | "graph_query_depth_exceeded"
        ) {
            mapped =
                mapped.with_hint("Reduce --max-results/--depth to fit bounded graph query limits");
        } else if matches!(
            mapped.code.as_str(),
            "graph_query_node_not_found" | "graph_query_node_ambiguous"
        ) {
            mapped = mapped.with_hint(
                    "Use 'hivemind graph query filter <project> --type file' to inspect available node IDs",
                );
        }
        mapped
    }

    pub(crate) fn encode_runtime_graph_query_gate_error(error: &HivemindError) -> String {
        let payload = RuntimeGraphQueryGateError {
            code: error.code.clone(),
            message: error.message.clone(),
            hint: error.recovery_hint.clone().or_else(|| {
                if error.code.starts_with("graph_snapshot_") {
                    Some(GRAPH_QUERY_REFRESH_HINT.to_string())
                } else {
                    None
                }
            }),
        };
        serde_json::to_string(&payload).unwrap_or_else(|_| {
            "{\"code\":\"graph_snapshot_invalid\",\"message\":\"graph query gate failed\"}"
                .to_string()
        })
    }

    pub(crate) fn set_native_graph_query_runtime_env(
        &self,
        project: &Project,
        runtime_env: &mut HashMap<String, String>,
        origin: &'static str,
    ) {
        runtime_env.remove(GRAPH_QUERY_ENV_GATE_ERROR);
        runtime_env.remove(GRAPH_QUERY_ENV_SNAPSHOT_PATH);
        runtime_env.remove(GRAPH_QUERY_ENV_CONSTITUTION_PATH);

        if project.repositories.is_empty() {
            return;
        }

        match self.ensure_graph_snapshot_current_for_constitution(project, origin) {
            Ok(()) => {
                runtime_env.insert(
                    GRAPH_QUERY_ENV_SNAPSHOT_PATH.to_string(),
                    self.graph_snapshot_path(project.id)
                        .to_string_lossy()
                        .to_string(),
                );
                runtime_env.insert(
                    GRAPH_QUERY_ENV_CONSTITUTION_PATH.to_string(),
                    self.constitution_path(project.id)
                        .to_string_lossy()
                        .to_string(),
                );
            }
            Err(error) => {
                runtime_env.insert(
                    GRAPH_QUERY_ENV_GATE_ERROR.to_string(),
                    Self::encode_runtime_graph_query_gate_error(&error),
                );
            }
        }
    }

    pub fn graph_query_execute(
        &self,
        id_or_name: &str,
        request: &GraphQueryRequest,
        source: &str,
    ) -> Result<GraphQueryResult> {
        let origin = "registry:graph_query_execute";
        let project = self
            .get_project(id_or_name)
            .inspect_err(|err| self.record_error_event(err, CorrelationIds::none()))?;
        self.ensure_graph_snapshot_current_for_constitution(&project, origin)?;
        let snapshot = self
            .read_graph_snapshot_artifact(project.id, origin)?
            .ok_or_else(|| {
                HivemindError::user(
                    "graph_snapshot_missing",
                    "Graph snapshot is missing for this project",
                    origin,
                )
                .with_hint("Run: hivemind graph snapshot refresh <project>")
            })?;

        let partition_paths =
            load_partition_paths_from_constitution(&self.constitution_path(project.id));
        let repositories = snapshot
            .repositories
            .iter()
            .map(|repo| GraphQueryRepository {
                repo_name: repo.repo_name.clone(),
                document: repo.document.clone(),
            })
            .collect::<Vec<_>>();
        let index = GraphQueryIndex::from_snapshot_repositories(&repositories, &partition_paths)
            .map_err(Self::map_graph_query_error)?;
        let started = Instant::now();
        let mut result = index
            .execute(
                request,
                &snapshot.canonical_fingerprint,
                &GraphQueryBounds::default(),
            )
            .map_err(Self::map_graph_query_error)?;
        let duration_ms = u64::try_from(started.elapsed().as_millis()).unwrap_or(u64::MAX);
        result.duration_ms = duration_ms;
        self.append_graph_query_executed_event(
            project.id,
            None,
            None,
            None,
            source,
            &result,
            duration_ms,
            CorrelationIds::for_project(project.id),
            origin,
        )?;
        Ok(result)
    }

    pub fn get_graph(&self, graph_id: &str) -> Result<TaskGraph> {
        let id = Uuid::parse_str(graph_id).map_err(|_| {
            HivemindError::user(
                "invalid_graph_id",
                format!("'{graph_id}' is not a valid graph ID"),
                "registry:get_graph",
            )
        })?;

        let state = self.state()?;
        state.graphs.get(&id).cloned().ok_or_else(|| {
            HivemindError::user(
                "graph_not_found",
                format!("Graph '{graph_id}' not found"),
                "registry:get_graph",
            )
        })
    }

    pub fn create_graph(
        &self,
        project_id_or_name: &str,
        name: &str,
        from_tasks: &[Uuid],
    ) -> Result<TaskGraph> {
        let project = self
            .get_project(project_id_or_name)
            .inspect_err(|err| self.record_error_event(err, CorrelationIds::none()))?;
        let state = self.state()?;

        let mut tasks_to_add = Vec::new();
        for tid in from_tasks {
            let task = state.tasks.get(tid).cloned().ok_or_else(|| {
                let err = HivemindError::user(
                    "task_not_found",
                    format!("Task '{tid}' not found"),
                    "registry:create_graph",
                );
                self.record_error_event(&err, CorrelationIds::for_project(project.id));
                err
            })?;
            if task.state != TaskState::Open {
                let err = HivemindError::user(
                    "task_not_open",
                    format!("Task '{tid}' is not open"),
                    "registry:create_graph",
                );
                self.record_error_event(&err, CorrelationIds::for_project(project.id));
                return Err(err);
            }
            tasks_to_add.push(task);
        }

        let graph_id = Uuid::new_v4();
        let event = Event::new(
            EventPayload::TaskGraphCreated {
                graph_id,
                project_id: project.id,
                name: name.to_string(),
                description: None,
            },
            CorrelationIds::for_graph(project.id, graph_id),
        );

        self.store.append(event).map_err(|e| {
            HivemindError::system(
                "event_append_failed",
                e.to_string(),
                "registry:create_graph",
            )
        })?;

        for task in tasks_to_add {
            let graph_task = GraphTask {
                id: task.id,
                title: task.title,
                description: task.description,
                criteria: SuccessCriteria::new("Done"),
                retry_policy: RetryPolicy::default(),
                checkpoints: vec!["checkpoint-1".to_string()],
                scope: task.scope,
            };
            let event = Event::new(
                EventPayload::TaskAddedToGraph {
                    graph_id,
                    task: graph_task,
                },
                CorrelationIds::for_graph(project.id, graph_id),
            );
            self.store.append(event).map_err(|e| {
                HivemindError::system(
                    "event_append_failed",
                    e.to_string(),
                    "registry:create_graph",
                )
            })?;
        }

        self.get_graph(&graph_id.to_string())
    }

    #[allow(clippy::too_many_lines)]
    pub fn add_graph_dependency(
        &self,
        graph_id: &str,
        from_task: &str,
        to_task: &str,
    ) -> Result<TaskGraph> {
        let gid = Uuid::parse_str(graph_id).map_err(|_| {
            let err = HivemindError::user(
                "invalid_graph_id",
                format!("'{graph_id}' is not a valid graph ID"),
                "registry:add_graph_dependency",
            );
            self.record_error_event(&err, CorrelationIds::none());
            err
        })?;
        let from = Uuid::parse_str(from_task).map_err(|_| {
            let err = HivemindError::user(
                "invalid_task_id",
                format!("'{from_task}' is not a valid task ID"),
                "registry:add_graph_dependency",
            );
            self.record_error_event(&err, CorrelationIds::none());
            err
        })?;
        let to = Uuid::parse_str(to_task).map_err(|_| {
            let err = HivemindError::user(
                "invalid_task_id",
                format!("'{to_task}' is not a valid task ID"),
                "registry:add_graph_dependency",
            );
            self.record_error_event(&err, CorrelationIds::none());
            err
        })?;

        let state = self.state()?;
        let graph = state.graphs.get(&gid).cloned().ok_or_else(|| {
            let err = HivemindError::user(
                "graph_not_found",
                format!("Graph '{graph_id}' not found"),
                "registry:add_graph_dependency",
            );
            self.record_error_event(&err, CorrelationIds::none());
            err
        })?;

        if graph.state != GraphState::Draft {
            let locking_flow_id = state
                .flows
                .values()
                .filter(|flow| flow.graph_id == gid)
                .max_by_key(|flow| flow.updated_at)
                .map(|flow| flow.id);
            let message = locking_flow_id.map_or_else(
                || format!("Graph '{graph_id}' is immutable"),
                |flow_id| format!("Graph '{graph_id}' is immutable (locked by flow '{flow_id}')"),
            );

            let mut err = HivemindError::user(
                    "graph_immutable",
                    message,
                    "registry:add_graph_dependency",
                )
                .with_hint(
                    "Create a new graph if you need additional dependencies, or modify task execution in the existing flow",
                );
            if let Some(flow_id) = locking_flow_id {
                err = err.with_context("locking_flow_id", flow_id.to_string());
            }
            self.record_error_event(&err, CorrelationIds::for_graph(graph.project_id, gid));
            return Err(err);
        }

        if !graph.tasks.contains_key(&from) || !graph.tasks.contains_key(&to) {
            let err = HivemindError::user(
                "task_not_in_graph",
                "One or more tasks are not in the graph",
                "registry:add_graph_dependency",
            )
            .with_hint("Ensure both task IDs were included when the graph was created");
            self.record_error_event(&err, CorrelationIds::for_graph(graph.project_id, gid));
            return Err(err);
        }

        if graph
            .dependencies
            .get(&to)
            .is_some_and(|deps| deps.contains(&from))
        {
            return Ok(graph);
        }

        let mut graph_for_check = graph.clone();
        graph_for_check.add_dependency(to, from).map_err(|e| {
            let err = HivemindError::user(
                "cycle_detected",
                e.to_string(),
                "registry:add_graph_dependency",
            )
            .with_hint("Remove one dependency in the cycle and try again");
            self.record_error_event(&err, CorrelationIds::for_graph(graph.project_id, gid));
            err
        })?;

        let event = Event::new(
            EventPayload::DependencyAdded {
                graph_id: gid,
                from_task: from,
                to_task: to,
            },
            CorrelationIds::for_graph(graph.project_id, gid),
        );

        self.store.append(event).map_err(|e| {
            HivemindError::system(
                "event_append_failed",
                e.to_string(),
                "registry:add_graph_dependency",
            )
        })?;

        self.get_graph(graph_id)
    }

    pub fn add_graph_task_check(
        &self,
        graph_id: &str,
        task_id: &str,
        check: crate::core::verification::CheckConfig,
    ) -> Result<TaskGraph> {
        let origin = "registry:add_graph_task_check";
        let gid = Uuid::parse_str(graph_id).map_err(|_| {
            let err = HivemindError::user(
                "invalid_graph_id",
                format!("'{graph_id}' is not a valid graph ID"),
                origin,
            );
            self.record_error_event(&err, CorrelationIds::none());
            err
        })?;
        let tid = Uuid::parse_str(task_id).map_err(|_| {
            let err = HivemindError::user(
                "invalid_task_id",
                format!("'{task_id}' is not a valid task ID"),
                origin,
            );
            self.record_error_event(&err, CorrelationIds::none());
            err
        })?;

        let state = self.state()?;
        let graph = state.graphs.get(&gid).cloned().ok_or_else(|| {
            let err = HivemindError::user(
                "graph_not_found",
                format!("Graph '{graph_id}' not found"),
                origin,
            );
            self.record_error_event(&err, CorrelationIds::none());
            err
        })?;
        if graph.state != GraphState::Draft {
            let err = HivemindError::user(
                "graph_immutable",
                format!("Graph '{graph_id}' is immutable"),
                origin,
            )
            .with_hint("Checks can only be added to draft graphs");
            self.record_error_event(&err, CorrelationIds::for_graph(graph.project_id, graph.id));
            return Err(err);
        }
        if !graph.tasks.contains_key(&tid) {
            let err = HivemindError::user(
                "task_not_in_graph",
                format!("Task '{task_id}' is not part of graph '{graph_id}'"),
                origin,
            );
            self.record_error_event(&err, CorrelationIds::for_graph(graph.project_id, graph.id));
            return Err(err);
        }

        let event = Event::new(
            EventPayload::GraphTaskCheckAdded {
                graph_id: gid,
                task_id: tid,
                check,
            },
            CorrelationIds::for_graph(graph.project_id, gid),
        );
        self.store
            .append(event)
            .map_err(|e| HivemindError::system("event_append_failed", e.to_string(), origin))?;

        self.get_graph(graph_id)
    }

    pub(crate) fn validate_graph_issues(graph: &TaskGraph) -> Vec<String> {
        fn has_cycle(graph: &TaskGraph) -> bool {
            use std::collections::HashSet;

            fn visit(
                graph: &TaskGraph,
                node: Uuid,
                visited: &mut HashSet<Uuid>,
                stack: &mut HashSet<Uuid>,
            ) -> bool {
                if stack.contains(&node) {
                    return true;
                }
                if visited.contains(&node) {
                    return false;
                }

                visited.insert(node);
                stack.insert(node);

                if let Some(deps) = graph.dependencies.get(&node) {
                    for dep in deps {
                        if visit(graph, *dep, visited, stack) {
                            return true;
                        }
                    }
                }

                stack.remove(&node);
                false
            }

            let mut visited = HashSet::new();
            let mut stack = HashSet::new();
            for node in graph.tasks.keys() {
                if visit(graph, *node, &mut visited, &mut stack) {
                    return true;
                }
            }
            false
        }

        if graph.tasks.is_empty() {
            return vec!["Graph must contain at least one task".to_string()];
        }

        for (task_id, deps) in &graph.dependencies {
            if !graph.tasks.contains_key(task_id) {
                return vec![format!("Task not found: {task_id}")];
            }
            for dep in deps {
                if !graph.tasks.contains_key(dep) {
                    return vec![format!("Task not found: {dep}")];
                }
            }
        }

        if has_cycle(graph) {
            return vec!["Cycle detected in task dependencies".to_string()];
        }

        Vec::new()
    }

    pub fn validate_graph(&self, graph_id: &str) -> Result<GraphValidationResult> {
        let graph = self.get_graph(graph_id)?;
        let issues = Self::validate_graph_issues(&graph);
        Ok(GraphValidationResult {
            graph_id: graph.id,
            valid: issues.is_empty(),
            issues,
        })
    }

    /// Deletes a graph.
    ///
    /// # Errors
    /// Returns an error if the graph is referenced by any flow.
    pub fn delete_graph(&self, graph_id: &str) -> Result<Uuid> {
        let graph = self
            .get_graph(graph_id)
            .inspect_err(|err| self.record_error_event(err, CorrelationIds::none()))?;
        let state = self.state()?;

        if state.flows.values().any(|flow| flow.graph_id == graph.id) {
            let err = HivemindError::user(
                "graph_in_use",
                "Graph is referenced by an existing flow",
                "registry:delete_graph",
            )
            .with_hint("Delete the flow(s) that reference this graph first");
            self.record_error_event(&err, CorrelationIds::for_graph(graph.project_id, graph.id));
            return Err(err);
        }

        let event = Event::new(
            EventPayload::TaskGraphDeleted {
                graph_id: graph.id,
                project_id: graph.project_id,
            },
            CorrelationIds::for_graph(graph.project_id, graph.id),
        );
        self.store.append(event).map_err(|e| {
            HivemindError::system(
                "event_append_failed",
                e.to_string(),
                "registry:delete_graph",
            )
        })?;

        Ok(graph.id)
    }
}
