//! Auto-generated registry split module: runtime.
//!
//! Generated by `scripts/registry_split_migrator.py`.
#![allow(clippy::wildcard_imports, unused_imports)]

use crate::core::registry::shared_prelude::*;
use crate::core::registry::shared_types::*;
use crate::core::registry::types::*;
use crate::core::registry::{
    Registry, ATTEMPT_CONTEXT_MAX_EXPAND_DEPTH, ATTEMPT_CONTEXT_SCHEMA_VERSION,
    ATTEMPT_CONTEXT_SECTION_BUDGET_BYTES, ATTEMPT_CONTEXT_TOTAL_BUDGET_BYTES,
    ATTEMPT_CONTEXT_TRUNCATION_POLICY, ATTEMPT_CONTEXT_VERSION, CONSTITUTION_SCHEMA_VERSION,
    CONSTITUTION_VERSION, GOVERNANCE_EXPORT_IMPORT_BOUNDARY, GOVERNANCE_FROM_LAYOUT,
    GOVERNANCE_PROJECTION_VERSION, GOVERNANCE_RECOVERY_SNAPSHOT_SCHEMA_VERSION,
    GOVERNANCE_SCHEMA_VERSION, GOVERNANCE_TO_LAYOUT, GRAPH_SNAPSHOT_SCHEMA_VERSION,
    GRAPH_SNAPSHOT_VERSION,
};

mod management;
mod native_events;

impl Registry {
    pub(crate) fn runtime_env_build_error(
        error: RuntimeEnvBuildError,
        origin: &'static str,
    ) -> HivemindError {
        HivemindError::runtime(error.code, error.message, origin).recoverable(false)
    }

    pub(crate) fn runtime_start_flags(runtime: &ProjectRuntimeConfig) -> Vec<String> {
        match runtime.adapter_name.as_str() {
            "codex" => {
                let mut flags = if runtime.args.is_empty() {
                    CodexConfig::default().base.args
                } else {
                    runtime.args.clone()
                };

                if let Some(model) = runtime.model.as_ref() {
                    if !Self::has_model_flag(&flags, false) {
                        flags.extend(["--model".to_string(), model.clone()]);
                    }
                }

                flags
            }
            "claude-code" => {
                let mut flags = if runtime.args.is_empty() {
                    ClaudeCodeConfig::default().base.args
                } else {
                    runtime.args.clone()
                };

                if let Some(model) = runtime.model.as_ref() {
                    if !Self::has_model_flag(&flags, false) {
                        flags.extend(["--model".to_string(), model.clone()]);
                    }
                }

                flags
            }
            "opencode" | "kilo" => {
                let mut flags = runtime.args.clone();
                let is_opencode_binary = PathBuf::from(&runtime.binary_path)
                    .file_name()
                    .and_then(|s| s.to_str())
                    .is_some_and(|s| {
                        let lower = s.to_ascii_lowercase();
                        lower.contains("opencode") || lower.contains("kilo")
                    });

                if is_opencode_binary {
                    let mut with_start = vec!["run".to_string()];
                    if let Some(model) = runtime.model.as_ref() {
                        if !Self::has_model_flag(&flags, true) {
                            with_start.extend(["--model".to_string(), model.clone()]);
                        }
                    }
                    with_start.append(&mut flags);
                    with_start
                } else {
                    flags
                }
            }
            "native" => {
                let mut flags = vec![
                    format!("--max-turns={}", NativeRuntimeConfig::default().max_turns),
                    format!(
                        "--token-budget={}",
                        NativeRuntimeConfig::default().token_budget
                    ),
                ];
                flags.extend(runtime.args.clone());
                flags
            }
            _ => runtime.args.clone(),
        }
    }

    pub(crate) fn runtime_descriptor_for_adapter(
        adapter: &str,
    ) -> Option<crate::adapters::RuntimeDescriptor> {
        runtime_descriptors()
            .into_iter()
            .find(|descriptor| descriptor.adapter_name == adapter)
    }

    pub(crate) fn runtime_capabilities_for_adapter(adapter: &str) -> Vec<String> {
        Self::runtime_descriptor_for_adapter(adapter)
            .map(|descriptor| {
                descriptor
                    .capabilities
                    .iter()
                    .map(|capability| (*capability).to_string())
                    .collect::<Vec<_>>()
            })
            .unwrap_or_default()
    }

    pub(crate) fn classify_runtime_error(
        code: &str,
        message: &str,
        recoverable: bool,
        stdout: &str,
        stderr: &str,
    ) -> ClassifiedRuntimeError {
        let combined = format!("{code} {message} {stdout} {stderr}").to_ascii_lowercase();
        let rate_limited = combined.contains("rate limit")
            || combined.contains("rate_limit")
            || combined.contains("too many requests")
            || combined.contains(" 429")
            || combined.contains("status 429")
            || combined.contains("http 429");

        let category = if rate_limited {
            "rate_limit"
        } else if code.starts_with("native_stream_") {
            "transport_stream"
        } else if code.starts_with("native_transport_") {
            "transport"
        } else if code == "timeout" {
            "timeout"
        } else if code == "checkpoints_incomplete" {
            "checkpoint_incomplete"
        } else if matches!(
            code,
            "binary_not_found" | "health_check_failed" | "missing_args" | "worktree_not_found"
        ) {
            "configuration"
        } else if code.contains("initialize") || code.contains("prepare") {
            "runtime_setup"
        } else {
            "runtime_execution"
        };

        let effective_recoverable = recoverable || rate_limited || code == "checkpoints_incomplete";
        let retryable = effective_recoverable
            && !matches!(
                code,
                "binary_not_found"
                    | "health_check_failed"
                    | "missing_args"
                    | "worktree_not_found"
                    | "checkpoints_incomplete"
            );

        ClassifiedRuntimeError {
            code: code.to_string(),
            category: category.to_string(),
            message: message.to_string(),
            recoverable: effective_recoverable,
            retryable,
            rate_limited,
        }
    }

    pub(crate) fn detect_runtime_output_failure(
        stdout: &str,
        stderr: &str,
    ) -> Option<(String, String, bool)> {
        let combined = format!("{stdout}\n{stderr}").to_ascii_lowercase();

        if combined.contains("incorrect api key")
            || combined.contains("invalid api key")
            || combined.contains("authentication failed")
            || combined.contains("unauthorized")
            || combined.contains("forbidden")
        {
            return Some((
                "runtime_auth_failed".to_string(),
                "Runtime authentication failed; inspect runtime stderr for details".to_string(),
                false,
            ));
        }

        if combined.contains("rate limit")
            || combined.contains("too many requests")
            || combined.contains("http 429")
            || combined.contains("status 429")
            || combined.contains(" 429")
        {
            return Some((
                "runtime_rate_limited".to_string(),
                "Runtime reported rate limiting; retry recommended".to_string(),
                true,
            ));
        }

        None
    }

    pub(crate) fn emit_runtime_error_classified(
        &self,
        flow: &TaskFlow,
        task_id: Uuid,
        attempt_id: Uuid,
        adapter_name: &str,
        classified: &ClassifiedRuntimeError,
        origin: &'static str,
    ) -> Result<()> {
        let corr_attempt = CorrelationIds::for_graph_flow_task_attempt(
            flow.project_id,
            flow.graph_id,
            flow.id,
            task_id,
            attempt_id,
        );

        self.append_event(
            Event::new(
                EventPayload::RuntimeErrorClassified {
                    attempt_id,
                    adapter_name: adapter_name.to_string(),
                    code: classified.code.clone(),
                    category: classified.category.clone(),
                    message: classified.message.clone(),
                    recoverable: classified.recoverable,
                    retryable: classified.retryable,
                    rate_limited: classified.rate_limited,
                },
                corr_attempt.clone(),
            ),
            origin,
        )?;

        let mut err = HivemindError::runtime(
            format!("runtime_{}", classified.code),
            classified.message.clone(),
            origin,
        )
        .recoverable(classified.recoverable)
        .with_context("adapter", adapter_name.to_string())
        .with_context("runtime_error_code", classified.code.clone())
        .with_context("runtime_error_category", classified.category.clone());

        if classified.rate_limited {
            err = err.with_hint(
                    "Rate limiting detected. Hivemind will schedule a retry and may switch to a backup runtime if configured.",
                );
        }

        self.record_error_event(&err, corr_attempt);
        Ok(())
    }

    pub(crate) fn select_runtime_backup(
        state: &AppState,
        flow: &TaskFlow,
        task_id: Uuid,
        primary: &ProjectRuntimeConfig,
    ) -> Option<ProjectRuntimeConfig> {
        if let Ok(candidate) = Self::effective_runtime_for_task(
            state,
            flow,
            task_id,
            RuntimeRole::Validator,
            "registry:tick_flow",
        ) {
            if candidate != *primary {
                return Some(candidate);
            }
        }

        match primary.adapter_name.as_str() {
            "opencode" => {
                let mut fallback = primary.clone();
                fallback.adapter_name = "kilo".to_string();
                Some(fallback)
            }
            "kilo" => {
                let mut fallback = primary.clone();
                fallback.adapter_name = "opencode".to_string();
                Some(fallback)
            }
            _ => None,
        }
    }

    #[allow(clippy::too_many_arguments)]
    pub(crate) fn schedule_runtime_recovery(
        &self,
        state: &AppState,
        flow: &TaskFlow,
        task_id: Uuid,
        attempt_id: Uuid,
        from_runtime: &ProjectRuntimeConfig,
        classified: &ClassifiedRuntimeError,
        origin: &'static str,
    ) -> Result<()> {
        let backup = Self::select_runtime_backup(state, flow, task_id, from_runtime);
        let target_runtime = if classified.rate_limited {
            backup.unwrap_or_else(|| from_runtime.clone())
        } else {
            from_runtime.clone()
        };

        let strategy = if target_runtime.adapter_name == from_runtime.adapter_name {
            "same_runtime_retry"
        } else {
            "fallback_runtime"
        };
        let backoff_ms = if classified.rate_limited { 1_000 } else { 250 };

        let corr_attempt = CorrelationIds::for_graph_flow_task_attempt(
            flow.project_id,
            flow.graph_id,
            flow.id,
            task_id,
            attempt_id,
        );
        self.append_event(
            Event::new(
                EventPayload::RuntimeRecoveryScheduled {
                    attempt_id,
                    from_adapter: from_runtime.adapter_name.clone(),
                    to_adapter: target_runtime.adapter_name.clone(),
                    strategy: strategy.to_string(),
                    reason: classified.code.clone(),
                    backoff_ms,
                },
                corr_attempt,
            ),
            origin,
        )?;

        if target_runtime.adapter_name != from_runtime.adapter_name {
            let corr_task = CorrelationIds::for_graph_flow_task(
                flow.project_id,
                flow.graph_id,
                flow.id,
                task_id,
            );
            self.append_event(
                Event::new(
                    EventPayload::TaskRuntimeRoleConfigured {
                        task_id,
                        role: RuntimeRole::Worker,
                        adapter_name: target_runtime.adapter_name,
                        binary_path: target_runtime.binary_path,
                        model: target_runtime.model,
                        args: target_runtime.args,
                        env: target_runtime.env,
                        timeout_ms: target_runtime.timeout_ms,
                    },
                    corr_task,
                ),
                origin,
            )?;
        }
        Ok(())
    }

    #[allow(clippy::too_many_arguments)]
    pub(crate) fn handle_runtime_failure(
        &self,
        state: &AppState,
        flow: &TaskFlow,
        task_id: Uuid,
        attempt_id: Uuid,
        runtime: &ProjectRuntimeConfig,
        next_attempt_number: u32,
        max_attempts: u32,
        failure_code: &str,
        failure_message: &str,
        recoverable: bool,
        stdout: &str,
        stderr: &str,
        origin: &'static str,
    ) -> Result<()> {
        let corr_attempt = CorrelationIds::for_graph_flow_task_attempt(
            flow.project_id,
            flow.graph_id,
            flow.id,
            task_id,
            attempt_id,
        );

        let reason = format!("{failure_code}: {failure_message}");
        self.append_event(
            Event::new(
                EventPayload::RuntimeTerminated { attempt_id, reason },
                corr_attempt.clone(),
            ),
            origin,
        )?;

        let classified = Self::classify_runtime_error(
            failure_code,
            failure_message,
            recoverable,
            stdout,
            stderr,
        );
        self.emit_runtime_error_classified(
            flow,
            task_id,
            attempt_id,
            &runtime.adapter_name,
            &classified,
            origin,
        )?;

        if failure_code == "checkpoints_incomplete" {
            return Ok(());
        }

        self.fail_running_attempt(flow, task_id, attempt_id, failure_code, origin)?;

        let should_retry = classified.retryable
            && next_attempt_number < max_attempts
            && (classified.rate_limited
                || matches!(
                    classified.code.as_str(),
                    "timeout" | "wait_failed" | "stdin_write_failed"
                )
                || classified.code.starts_with("native_transport_")
                || classified.code.starts_with("native_stream_"));

        if should_retry {
            self.schedule_runtime_recovery(
                state,
                flow,
                task_id,
                attempt_id,
                runtime,
                &classified,
                origin,
            )?;
            if let Err(err) = self.retry_task(&task_id.to_string(), false, RetryMode::Continue) {
                self.record_error_event(&err, corr_attempt);
            }
        }

        Ok(())
    }
}
