    ChatSessionCreated {
        session_id: Uuid,
        mode: String,
        title: String,
        project_id: Option<Uuid>,
        task_id: Option<Uuid>,
        flow_id: Option<Uuid>,
    },
    ChatSessionTitleUpdated {
        session_id: Uuid,
        title: String,
    },
    ChatMessageAppended {
        session_id: Uuid,
        message_id: Uuid,
        role: String,
        content: String,
        request_id: Option<String>,
        provider: Option<String>,
        model: Option<String>,
        final_state: Option<String>,
        runtime_selection_source: Option<String>,
    },
    ChatStreamChunkAppended {
        session_id: Uuid,
        message_id: Uuid,
        request_id: String,
        turn_index: u32,
        from_state: String,
        to_state: String,
        directive_kind: String,
        content: String,
    },