//! Auto-generated registry split module: context.
//!
//! Generated by scripts/registry_split_migrator.py.

use crate::core::registry::Registry;

impl Registry {
        #[allow(clippy::too_many_lines, clippy::too_many_arguments)]
        fn assemble_attempt_context(
            &self,
            state: &AppState,
            flow: &TaskFlow,
            task_id: Uuid,
            attempt_id: Uuid,
            runtime_name: &str,
            prior_attempt_ids: &[Uuid],
            origin: &'static str,
        ) -> Result<AttemptContextBuildResult> {
            let constitution_location = self.governance_constitution_location(flow.project_id);
            let constitution_raw = fs::read_to_string(&constitution_location.path).unwrap_or_default();
            let constitution_revision = Self::governance_artifact_revision(
                state,
                Some(flow.project_id),
                "project",
                "constitution",
                "constitution.yaml",
            );
            let constitution_digest = state
                .projects
                .get(&flow.project_id)
                .and_then(|project| project.constitution_digest.clone())
                .or_else(|| {
                    if constitution_raw.trim().is_empty() {
                        None
                    } else {
                        Some(Self::constitution_digest(constitution_raw.as_bytes()))
                    }
                });
            let constitution_content_hash = if constitution_raw.trim().is_empty() {
                None
            } else {
                Some(Self::constitution_digest(constitution_raw.as_bytes()))
            };
    
            let template_snapshot = self.latest_template_instantiation_snapshot(flow.project_id)?;
            let template_document_ids = template_snapshot
                .as_ref()
                .map_or_else(Vec::new, |item| item.document_ids.clone());
    
            let (attachment_included, attachment_excluded) =
                Self::governance_document_attachment_states(state, flow.project_id, task_id);
            let template_set: HashSet<&str> =
                template_document_ids.iter().map(String::as_str).collect();
    
            let mut included_document_ids: Vec<String> = attachment_included
                .iter()
                .filter(|id| !template_set.contains(id.as_str()))
                .cloned()
                .collect();
            included_document_ids.sort();
            included_document_ids.dedup();
    
            let mut excluded_document_ids = attachment_excluded;
            excluded_document_ids.sort();
            excluded_document_ids.dedup();
    
            let mut resolved_document_ids = template_document_ids.clone();
            for doc_id in &included_document_ids {
                if !resolved_document_ids.iter().any(|item| item == doc_id) {
                    resolved_document_ids.push(doc_id.clone());
                }
            }
            resolved_document_ids
                .retain(|id| !excluded_document_ids.iter().any(|excluded| excluded == id));
            resolved_document_ids.sort();
            resolved_document_ids.dedup();
    
            let mut document_manifest = Vec::new();
            let mut document_sections = Vec::new();
            for document_id in &resolved_document_ids {
                let artifact =
                    self.read_project_document_artifact(flow.project_id, document_id, origin)?;
                let latest = artifact.revisions.last().ok_or_else(|| {
                    HivemindError::user(
                        "governance_artifact_schema_invalid",
                        format!("Document '{document_id}' has no latest revision"),
                        origin,
                    )
                })?;
                let source = if template_set.contains(document_id.as_str()) {
                    "template"
                } else {
                    "attachment_include"
                };
                document_manifest.push(AttemptContextDocumentManifest {
                    document_id: document_id.clone(),
                    source: source.to_string(),
                    revision: latest.revision,
                    content_hash: Self::constitution_digest(latest.content.as_bytes()),
                });
                document_sections.push(format!(
                    "- document_id: {document_id}\n  source: {source}\n  revision: {}\n  title: {}\n  owner: {}\n  content:\n{}",
                    latest.revision,
                    artifact.title,
                    artifact.owner,
                    latest.content
                ));
            }
    
            let mut skill_manifest = Vec::new();
            let mut skill_sections = Vec::new();
            let mut system_prompt_manifest = None;
            let mut system_prompt_section = "System Prompt:\n- none selected".to_string();
            if let Some(template) = template_snapshot.as_ref() {
                let prompt =
                    self.read_global_system_prompt_artifact(&template.system_prompt_id, origin)?;
                system_prompt_manifest = Some(AttemptContextSystemPromptManifest {
                    prompt_id: prompt.prompt_id.clone(),
                    content_hash: Self::constitution_digest(prompt.content.as_bytes()),
                });
                system_prompt_section = format!(
                    "System Prompt:\n- prompt_id: {}\n- content:\n{}",
                    prompt.prompt_id, prompt.content
                );
    
                for skill_id in &template.skill_ids {
                    let skill = self.read_global_skill_artifact(skill_id, origin)?;
                    skill_manifest.push(AttemptContextSkillManifest {
                        skill_id: skill.skill_id.clone(),
                        content_hash: Self::constitution_digest(skill.content.as_bytes()),
                    });
                    skill_sections.push(format!(
                        "- skill_id: {}\n  name: {}\n  content:\n{}",
                        skill.skill_id, skill.name, skill.content
                    ));
                }
            }
    
            let graph_artifact = self.read_graph_snapshot_artifact(flow.project_id, origin)?;
            let graph_summary = graph_artifact.as_ref().map_or_else(
                || AttemptContextGraphManifest {
                    present: false,
                    canonical_fingerprint: None,
                    repository_count: 0,
                    total_nodes: 0,
                    total_edges: 0,
                    languages: BTreeMap::new(),
                },
                |item| AttemptContextGraphManifest {
                    present: true,
                    canonical_fingerprint: Some(item.canonical_fingerprint.clone()),
                    repository_count: item.repositories.len(),
                    total_nodes: item.summary.total_nodes,
                    total_edges: item.summary.total_edges,
                    languages: item.summary.languages.clone(),
                },
            );
    
            let graph_section = if graph_summary.present {
                let fingerprint = graph_summary
                    .canonical_fingerprint
                    .clone()
                    .unwrap_or_default();
                let languages = if graph_summary.languages.is_empty() {
                    "(none)".to_string()
                } else {
                    graph_summary
                        .languages
                        .iter()
                        .map(|(lang, count)| format!("{lang}:{count}"))
                        .collect::<Vec<_>>()
                        .join(", ")
                };
                format!(
                    "Graph Summary:\n- canonical_fingerprint: {fingerprint}\n- repositories: {}\n- total_nodes: {}\n- total_edges: {}\n- languages: {languages}",
                    graph_summary.repository_count, graph_summary.total_nodes, graph_summary.total_edges
                )
            } else {
                "Graph Summary:\n- status: unavailable".to_string()
            };
    
            let constitution_section = if constitution_raw.trim().is_empty() {
                "Constitution:\n- status: missing".to_string()
            } else {
                format!(
                    "Constitution:\n- path: {}\n- digest: {}\n- content:\n{}",
                    constitution_location.path.to_string_lossy(),
                    constitution_digest.clone().unwrap_or_default(),
                    constitution_raw
                )
            };
    
            let skills_section = if skill_sections.is_empty() {
                "Skills:\n- none selected".to_string()
            } else {
                format!("Skills:\n{}", skill_sections.join("\n\n"))
            };
            let documents_section = if document_sections.is_empty() {
                "Documents:\n- none selected".to_string()
            } else {
                format!("Documents:\n{}", document_sections.join("\n\n"))
            };
    
            let mut retry_links = Vec::new();
            let mut prior_manifest_hashes = Vec::new();
            for prior_id in prior_attempt_ids {
                let manifest_hash = self.attempt_manifest_hash_for_attempt(*prior_id)?;
                if let Some(hash) = manifest_hash.as_ref() {
                    prior_manifest_hashes.push(hash.clone());
                }
                retry_links.push(AttemptContextRetryLink {
                    attempt_id: *prior_id,
                    manifest_hash,
                });
            }
    
            let ordered_inputs = vec![
                "constitution".to_string(),
                "system_prompt".to_string(),
                "skills".to_string(),
                "project_documents".to_string(),
                "graph_summary".to_string(),
            ];
            let excluded_sources = vec![
                "project_notepad".to_string(),
                "global_notepad".to_string(),
                "implicit_memory".to_string(),
            ];
    
            let mut per_section_budget_bytes = BTreeMap::new();
            for section in &ordered_inputs {
                per_section_budget_bytes.insert(section.clone(), ATTEMPT_CONTEXT_SECTION_BUDGET_BYTES);
            }
            let budget_policy = ContextBudgetPolicy {
                total_budget_bytes: ATTEMPT_CONTEXT_TOTAL_BUDGET_BYTES,
                default_section_budget_bytes: ATTEMPT_CONTEXT_SECTION_BUDGET_BYTES,
                per_section_budget_bytes: per_section_budget_bytes.clone(),
                max_expand_depth: ATTEMPT_CONTEXT_MAX_EXPAND_DEPTH,
                deduplicate: true,
                truncation_policy: ATTEMPT_CONTEXT_TRUNCATION_POLICY.to_string(),
            };
    
            let context_window_id = format!("attempt-context-{attempt_id}");
            let mut window = ContextWindow::new(
                context_window_id.clone(),
                ordered_inputs.clone(),
                budget_policy,
            );
            let window_actor = ContextOperationActor {
                actor: "flow_engine".to_string(),
                runtime: Some(runtime_name.to_string()),
                tool: None,
            };
            let mut context_window_ops = Vec::new();
            context_window_ops.push(window.add_entry(
                ContextEntryCandidate {
                    entry_id: "constitution-primary".to_string(),
                    section: "constitution".to_string(),
                    content: constitution_section,
                    source: "governance_constitution".to_string(),
                    depth: 0,
                },
                "seed_constitution",
                window_actor.clone(),
            ));
            context_window_ops.push(window.add_entry(
                ContextEntryCandidate {
                    entry_id: "system-prompt-primary".to_string(),
                    section: "system_prompt".to_string(),
                    content: system_prompt_section,
                    source: "template_system_prompt".to_string(),
                    depth: 0,
                },
                "seed_system_prompt",
                window_actor.clone(),
            ));
            if skill_sections.is_empty() {
                context_window_ops.push(window.add_entry(
                    ContextEntryCandidate {
                        entry_id: "skills-none".to_string(),
                        section: "skills".to_string(),
                        content: skills_section,
                        source: "template_skills".to_string(),
                        depth: 0,
                    },
                    "seed_skills_empty",
                    window_actor.clone(),
                ));
            } else {
                context_window_ops.push(window.add_entry(
                    ContextEntryCandidate {
                        entry_id: "skills-header".to_string(),
                        section: "skills".to_string(),
                        content: "Skills:".to_string(),
                        source: "template_skills".to_string(),
                        depth: 0,
                    },
                    "seed_skills_header",
                    window_actor.clone(),
                ));
                let skill_candidates: Vec<ContextEntryCandidate> = skill_sections
                    .iter()
                    .enumerate()
                    .map(|(idx, content)| ContextEntryCandidate {
                        entry_id: format!("skills-entry-{idx:03}"),
                        section: "skills".to_string(),
                        content: content.clone(),
                        source: "template_skills".to_string(),
                        depth: 1,
                    })
                    .collect();
                context_window_ops.push(window.expand_entries(
                    skill_candidates,
                    "expand_skills",
                    window_actor.clone(),
                    true,
                ));
            }
            if document_sections.is_empty() {
                context_window_ops.push(window.add_entry(
                    ContextEntryCandidate {
                        entry_id: "documents-none".to_string(),
                        section: "project_documents".to_string(),
                        content: documents_section,
                        source: "project_documents".to_string(),
                        depth: 0,
                    },
                    "seed_documents_empty",
                    window_actor.clone(),
                ));
            } else {
                context_window_ops.push(window.add_entry(
                    ContextEntryCandidate {
                        entry_id: "documents-header".to_string(),
                        section: "project_documents".to_string(),
                        content: "Documents:".to_string(),
                        source: "project_documents".to_string(),
                        depth: 0,
                    },
                    "seed_documents_header",
                    window_actor.clone(),
                ));
                let document_candidates: Vec<ContextEntryCandidate> = document_sections
                    .iter()
                    .enumerate()
                    .map(|(idx, content)| ContextEntryCandidate {
                        entry_id: format!("documents-entry-{idx:03}"),
                        section: "project_documents".to_string(),
                        content: content.clone(),
                        source: "project_documents".to_string(),
                        depth: 1,
                    })
                    .collect();
                context_window_ops.push(window.expand_entries(
                    document_candidates,
                    "expand_documents",
                    window_actor.clone(),
                    true,
                ));
            }
            context_window_ops.push(window.add_entry(
                ContextEntryCandidate {
                    entry_id: "graph-summary-primary".to_string(),
                    section: "graph_summary".to_string(),
                    content: graph_section,
                    source: "graph_snapshot".to_string(),
                    depth: 0,
                },
                "seed_graph_summary",
                window_actor.clone(),
            ));
    
            let original_size_bytes: usize =
                window.entries.values().map(ContextEntry::size_bytes).sum();
            let prune_op = window.prune("enforce_budget_policy", window_actor.clone());
            context_window_ops.push(prune_op.clone());
            let (snapshot, snapshot_op) = window.snapshot("create_context_snapshot", window_actor);
            context_window_ops.push(snapshot_op);
    
            let context = snapshot.rendered_prompt.clone();
            let context_size_bytes = snapshot.total_size_bytes;
            let truncated_sections = prune_op.truncated_sections.clone();
            let truncation_reasons = prune_op.section_reasons;
    
            let manifest = AttemptContextManifest {
                schema_version: ATTEMPT_CONTEXT_SCHEMA_VERSION.to_string(),
                manifest_version: ATTEMPT_CONTEXT_VERSION,
                ordered_inputs: ordered_inputs.clone(),
                excluded_sources,
                constitution: AttemptContextConstitutionManifest {
                    path: constitution_location.path.to_string_lossy().to_string(),
                    revision: constitution_revision,
                    digest: constitution_digest,
                    content_hash: constitution_content_hash,
                },
                template_id: template_snapshot
                    .as_ref()
                    .map(|item| item.template_id.clone()),
                template_event_id: template_snapshot.as_ref().map(|item| item.event_id.clone()),
                template_schema_version: template_snapshot
                    .as_ref()
                    .map(|item| item.schema_version.clone()),
                template_projection_version: template_snapshot
                    .as_ref()
                    .map(|item| item.projection_version),
                system_prompt: system_prompt_manifest,
                skills: skill_manifest,
                documents: document_manifest,
                graph_summary,
                retry_links,
                budget: AttemptContextBudgetManifest {
                    total_budget_bytes: ATTEMPT_CONTEXT_TOTAL_BUDGET_BYTES,
                    default_section_budget_bytes: ATTEMPT_CONTEXT_SECTION_BUDGET_BYTES,
                    per_section_budget_bytes,
                    max_expand_depth: ATTEMPT_CONTEXT_MAX_EXPAND_DEPTH,
                    deduplicate: true,
                    original_size_bytes,
                    context_size_bytes,
                    truncated_sections: truncated_sections.clone(),
                    truncation_reasons: truncation_reasons.clone(),
                    policy: ATTEMPT_CONTEXT_TRUNCATION_POLICY.to_string(),
                },
            };
    
            let manifest_json = serde_json::to_string(&manifest).map_err(|e| {
                HivemindError::system("context_manifest_serialize_failed", e.to_string(), origin)
            })?;
            let manifest_hash = Self::constitution_digest(manifest_json.as_bytes());
            let inputs_fingerprint_payload = serde_json::json!({
                "ordered_inputs": ordered_inputs,
                "constitution": manifest.constitution,
                "template_id": manifest.template_id,
                "template_schema_version": manifest.template_schema_version,
                "template_projection_version": manifest.template_projection_version,
                "system_prompt": manifest.system_prompt,
                "skills": manifest.skills,
                "documents": manifest.documents,
                "graph_summary": manifest.graph_summary,
                "retry_manifest_hashes": prior_manifest_hashes,
                "budget": {
                    "total_budget_bytes": ATTEMPT_CONTEXT_TOTAL_BUDGET_BYTES,
                    "default_section_budget_bytes": ATTEMPT_CONTEXT_SECTION_BUDGET_BYTES,
                    "per_section_budget_bytes": manifest.budget.per_section_budget_bytes,
                    "max_expand_depth": ATTEMPT_CONTEXT_MAX_EXPAND_DEPTH,
                    "deduplicate": true,
                    "truncated_sections": manifest.budget.truncated_sections,
                    "truncation_reasons": manifest.budget.truncation_reasons,
                    "policy": ATTEMPT_CONTEXT_TRUNCATION_POLICY
                },
                "context_window": {
                    "state_hash": snapshot.state_hash
                },
            });
            let inputs_bytes = serde_json::to_vec(&inputs_fingerprint_payload).map_err(|e| {
                HivemindError::system("context_inputs_serialize_failed", e.to_string(), origin)
            })?;
            let inputs_hash = Self::constitution_digest(&inputs_bytes);
            let context_hash = Self::constitution_digest(context.as_bytes());
            let context_window_snapshot_json = serde_json::to_string(&snapshot).map_err(|e| {
                HivemindError::system(
                    "context_window_snapshot_serialize_failed",
                    e.to_string(),
                    origin,
                )
            })?;
    
            Ok(AttemptContextBuildResult {
                manifest_json,
                manifest_hash,
                inputs_hash,
                context,
                context_hash,
                original_size_bytes,
                context_size_bytes,
                truncated_sections,
                truncation_reasons,
                prior_manifest_hashes,
                context_window_id,
                context_window_state_hash: snapshot.state_hash,
                context_window_snapshot_json,
                context_window_ops,
                template_document_ids,
                included_document_ids,
                excluded_document_ids,
                resolved_document_ids,
            })
        }

}
