//! Auto-generated registry split module: events.
//!
//! Generated by scripts/registry_split_migrator.py.

use crate::core::registry::Registry;

impl Registry {
    
        fn append_event(&self, event: Event, origin: &'static str) -> Result<()> {
            self.store
                .append(event)
                .map(|_| ())
                .map_err(|e| HivemindError::system("event_append_failed", e.to_string(), origin))
        }

    
        fn record_error_event(&self, err: &HivemindError, correlation: CorrelationIds) {
            let _ = self.store.append(Event::new(
                EventPayload::ErrorOccurred { error: err.clone() },
                correlation,
            ));
        }

    
        pub fn read_events(&self, filter: &EventFilter) -> Result<Vec<Event>> {
            self.store.read(filter).map_err(|e| {
                HivemindError::system("event_read_failed", e.to_string(), "registry:read_events")
            })
        }

    
        pub fn stream_events(&self, filter: &EventFilter) -> Result<std::sync::mpsc::Receiver<Event>> {
            self.store.stream(filter).map_err(|e| {
                HivemindError::system(
                    "event_stream_failed",
                    e.to_string(),
                    "registry:stream_events",
                )
            })
        }

        /// Gets a specific event by ID.
        ///
        /// # Errors
        /// Returns an error if the event cannot be read or is not found.
        pub fn get_event(&self, event_id: &str) -> Result<Event> {
            let id = Uuid::parse_str(event_id).map_err(|_| {
                HivemindError::user(
                    "invalid_event_id",
                    format!("'{event_id}' is not a valid event ID"),
                    "registry:get_event",
                )
            })?;
    
            let events = self.store.read_all().map_err(|e| {
                HivemindError::system("event_read_failed", e.to_string(), "registry:get_event")
            })?;
    
            events
                .into_iter()
                .find(|e| e.metadata.id.as_uuid() == id)
                .ok_or_else(|| {
                    HivemindError::user(
                        "event_not_found",
                        format!("Event '{event_id}' not found"),
                        "registry:get_event",
                    )
                })
        }

    
        fn normalize_concatenated_json_objects(line: &str) -> String {
            let mut out = String::with_capacity(line.len());
            let mut chars = line.chars().peekable();
            let mut in_string = false;
            let mut escape = false;
    
            while let Some(c) = chars.next() {
                if in_string {
                    if escape {
                        escape = false;
                    } else if c == '\\' {
                        escape = true;
                    } else if c == '"' {
                        in_string = false;
                    }
                } else if c == '"' {
                    in_string = true;
                }
    
                out.push(c);
    
                if !in_string && c == '}' && chars.peek().copied() == Some('{') {
                    out.push('\n');
                }
            }
    
            out
        }

}
