//! Auto-generated registry split module: flow.
//!
//! Generated by scripts/registry_split_migrator.py.

use crate::core::registry::Registry;

impl Registry {
    
        fn format_checkpoint_commit_message(spec: &CheckpointCommitSpec<'_>) -> String {
            let mut message = String::new();
            let _ = writeln!(message, "hivemind(checkpoint): {}", spec.checkpoint_id);
            let _ = writeln!(message);
            let _ = writeln!(message, "Flow: {}", spec.flow_id);
            let _ = writeln!(message, "Task: {}", spec.task_id);
            let _ = writeln!(message, "Attempt: {}", spec.attempt_id);
            let _ = writeln!(message, "Checkpoint: {}/{}", spec.order, spec.total);
            let _ = writeln!(message, "Schema: checkpoint-v1");
            if let Some(summary) = spec.summary {
                let _ = writeln!(message);
                let _ = writeln!(message, "Summary:");
                let _ = writeln!(message, "{summary}");
            }
            let _ = writeln!(message);
            let _ = writeln!(message, "---");
            let _ = writeln!(
                message,
                "Generated-by: Hivemind {}",
                env!("CARGO_PKG_VERSION")
            );
            message
        }

    
        fn create_checkpoint_commit(
            worktree_path: &Path,
            spec: &CheckpointCommitSpec<'_>,
            origin: &'static str,
        ) -> Result<String> {
            let add = std::process::Command::new("git")
                .current_dir(worktree_path)
                .args(["add", "-A"])
                .output()
                .map_err(|e| HivemindError::git("git_add_failed", e.to_string(), origin))?;
            if !add.status.success() {
                return Err(HivemindError::git(
                    "git_add_failed",
                    String::from_utf8_lossy(&add.stderr).to_string(),
                    origin,
                ));
            }
    
            let message = Self::format_checkpoint_commit_message(spec);
            let commit = std::process::Command::new("git")
                .current_dir(worktree_path)
                .args([
                    "-c",
                    "user.name=Hivemind",
                    "-c",
                    "user.email=hivemind@example.com",
                    "commit",
                    "--allow-empty",
                    "-m",
                    &message,
                ])
                .output()
                .map_err(|e| HivemindError::git("git_commit_failed", e.to_string(), origin))?;
            if !commit.status.success() {
                return Err(HivemindError::git(
                    "git_commit_failed",
                    String::from_utf8_lossy(&commit.stderr).to_string(),
                    origin,
                ));
            }
    
            let head = std::process::Command::new("git")
                .current_dir(worktree_path)
                .args(["rev-parse", "HEAD"])
                .output()
                .map_err(|e| HivemindError::git("git_rev_parse_failed", e.to_string(), origin))?;
            if !head.status.success() {
                return Err(HivemindError::git(
                    "git_rev_parse_failed",
                    String::from_utf8_lossy(&head.stderr).to_string(),
                    origin,
                ));
            }
            Ok(String::from_utf8_lossy(&head.stdout).trim().to_string())
        }

    
        fn checkout_and_clean_worktree(
            worktree_path: &Path,
            branch: &str,
            base: &str,
            origin: &'static str,
        ) -> Result<()> {
            let checkout = std::process::Command::new("git")
                .current_dir(worktree_path)
                .args(["checkout", "-f", "-B", branch, base])
                .output();
            if !checkout.as_ref().is_ok_and(|o| o.status.success()) {
                return Err(HivemindError::git(
                    "git_checkout_failed",
                    checkout.map_or_else(
                        |e| e.to_string(),
                        |o| String::from_utf8_lossy(&o.stderr).to_string(),
                    ),
                    origin,
                ));
            }
    
            let clean = std::process::Command::new("git")
                .current_dir(worktree_path)
                .args(["clean", "-fdx"])
                .output();
            if !clean.as_ref().is_ok_and(|o| o.status.success()) {
                return Err(HivemindError::git(
                    "git_clean_failed",
                    clean.map_or_else(
                        |e| e.to_string(),
                        |o| String::from_utf8_lossy(&o.stderr).to_string(),
                    ),
                    origin,
                ));
            }
    
            Ok(())
        }

    
        fn acquire_flow_integration_lock(
            &self,
            flow_id: Uuid,
            origin: &'static str,
        ) -> Result<std::fs::File> {
            let lock_dir = self.config.data_dir.join("locks");
            fs::create_dir_all(&lock_dir)
                .map_err(|e| HivemindError::system("create_dir_failed", e.to_string(), origin))?;
    
            let lock_path = lock_dir.join(format!("flow_integration_{flow_id}.lock"));
            for attempt in 0..5 {
                let file = OpenOptions::new()
                    .create(true)
                    .read(true)
                    .write(true)
                    .truncate(false)
                    .open(&lock_path)
                    .map_err(|e| HivemindError::system("lock_open_failed", e.to_string(), origin))?;
    
                match file.try_lock_exclusive() {
                    Ok(()) => return Ok(file),
                    Err(err) => {
                        if attempt < 4 {
                            std::thread::sleep(Duration::from_millis(20));
                            continue;
                        }
                        return Err(HivemindError::user(
                            "integration_in_progress",
                            "Another integration operation is already in progress for this flow",
                            origin,
                        )
                        .with_context("flow_id", flow_id.to_string())
                        .with_context("lock_error", err.to_string()));
                    }
                }
            }
    
            Err(HivemindError::user(
                "integration_in_progress",
                "Another integration operation is already in progress for this flow",
                origin,
            )
            .with_context("flow_id", flow_id.to_string())
            .with_context("lock_error", "retry_exhausted"))
        }

    
        fn resolve_git_ref(repo_path: &Path, reference: &str) -> Option<String> {
            let output = std::process::Command::new("git")
                .current_dir(repo_path)
                .args(["rev-parse", reference])
                .output()
                .ok()?;
            if !output.status.success() {
                return None;
            }
    
            let sha = String::from_utf8_lossy(&output.stdout).trim().to_string();
            if sha.is_empty() {
                return None;
            }
            Some(sha)
        }

    
        fn resolve_task_frozen_commit_sha(
            flow: &TaskFlow,
            state: &AppState,
            task_id: Uuid,
        ) -> Option<String> {
            let manager = Self::worktree_manager_for_flow(flow, state).ok()?;
            let branch_ref = format!("refs/heads/exec/{}/{task_id}", flow.id);
            Self::resolve_git_ref(manager.repo_path(), &branch_ref).or_else(|| {
                let status = manager.inspect(flow.id, task_id).ok()?;
                if !status.is_worktree {
                    return None;
                }
                status
                    .head_commit
                    .or_else(|| Self::resolve_git_ref(&status.path, "HEAD"))
            })
        }

    
        fn emit_task_execution_frozen(
            &self,
            flow: &TaskFlow,
            task_id: Uuid,
            commit_sha: Option<String>,
            origin: &'static str,
        ) -> Result<()> {
            self.append_event(
                Event::new(
                    EventPayload::TaskExecutionFrozen {
                        flow_id: flow.id,
                        task_id,
                        commit_sha,
                    },
                    CorrelationIds::for_graph_flow_task(
                        flow.project_id,
                        flow.graph_id,
                        flow.id,
                        task_id,
                    ),
                ),
                origin,
            )
        }

    
        fn emit_integration_lock_acquired(
            &self,
            flow: &TaskFlow,
            operation: &str,
            origin: &'static str,
        ) -> Result<()> {
            self.append_event(
                Event::new(
                    EventPayload::FlowIntegrationLockAcquired {
                        flow_id: flow.id,
                        operation: operation.to_string(),
                    },
                    CorrelationIds::for_graph_flow(flow.project_id, flow.graph_id, flow.id),
                ),
                origin,
            )
        }

    
        fn emit_merge_conflict(
            &self,
            flow: &TaskFlow,
            task_id: Option<Uuid>,
            details: String,
            origin: &'static str,
        ) -> Result<()> {
            self.append_event(
                Event::new(
                    EventPayload::MergeConflictDetected {
                        flow_id: flow.id,
                        task_id,
                        details,
                    },
                    CorrelationIds::for_graph_flow(flow.project_id, flow.graph_id, flow.id),
                ),
                origin,
            )
        }

    
        fn attempt_runtime_outcome(&self, attempt_id: Uuid) -> Result<(Option<i32>, Option<String>)> {
            let filter = EventFilter {
                attempt_id: Some(attempt_id),
                ..EventFilter::default()
            };
            let events = self.read_events(&filter)?;
    
            let mut exit_code: Option<i32> = None;
            let mut terminated: Option<String> = None;
            for ev in events {
                match ev.payload {
                    EventPayload::RuntimeExited { exit_code: ec, .. } => {
                        exit_code = Some(ec);
                    }
                    EventPayload::RuntimeTerminated { reason, .. } => {
                        terminated = Some(reason);
                    }
                    _ => {}
                }
            }
    
            if exit_code.is_none() && terminated.is_none() {
                return Ok((None, None));
            }
            Ok((exit_code, terminated))
        }

        fn build_retry_context(
            &self,
            state: &AppState,
            flow: &TaskFlow,
            task_id: Uuid,
            attempt_number: u32,
            max_attempts: u32,
            _origin: &'static str,
        ) -> Result<(
            String,
            Vec<AttemptSummary>,
            Vec<Uuid>,
            Vec<String>,
            Vec<String>,
            Option<i32>,
            Option<String>,
        )> {
            let mut attempts: Vec<AttemptState> = state
                .attempts
                .values()
                .filter(|a| a.flow_id == flow.id && a.task_id == task_id)
                .filter(|a| a.attempt_number < attempt_number)
                .cloned()
                .collect();
            attempts.sort_by_key(|a| a.attempt_number);
    
            let prior_attempt_ids: Vec<Uuid> = attempts.iter().map(|a| a.id).collect();
    
            let mut prior_attempts: Vec<AttemptSummary> = Vec::new();
            for prior in &attempts {
                let (exit_code, terminated_reason) = self
                    .attempt_runtime_outcome(prior.id)
                    .unwrap_or((None, None));
    
                let required_failed: Vec<String> = prior
                    .check_results
                    .iter()
                    .filter(|r| r.required && !r.passed)
                    .map(|r| r.name.clone())
                    .collect();
                let optional_failed: Vec<String> = prior
                    .check_results
                    .iter()
                    .filter(|r| !r.required && !r.passed)
                    .map(|r| r.name.clone())
                    .collect();
                let incomplete_checkpoints: Vec<String> = prior
                    .checkpoints
                    .iter()
                    .filter(|cp| cp.state != AttemptCheckpointState::Completed)
                    .map(|cp| cp.checkpoint_id.clone())
                    .collect();
    
                let mut summary = String::new();
                if let Some(diff_id) = prior.diff_id {
                    if let Ok(artifact) = self.read_diff_artifact(diff_id) {
                        let _ = write!(summary, "change_count={} ", artifact.diff.change_count());
                    }
                }
    
                if required_failed.is_empty() && optional_failed.is_empty() {
                    if let Some(ec) = exit_code {
                        let _ = write!(summary, "runtime_exit_code={ec} ");
                    }
                    if let Some(ref reason) = terminated_reason {
                        let _ = write!(summary, "runtime_terminated={reason} ");
                    }
                }
    
                if !required_failed.is_empty() {
                    let _ = write!(
                        summary,
                        "required_checks_failed={} ",
                        required_failed.join(", ")
                    );
                }
                if !optional_failed.is_empty() {
                    let _ = write!(
                        summary,
                        "optional_checks_failed={} ",
                        optional_failed.join(", ")
                    );
                }
                if !incomplete_checkpoints.is_empty() {
                    let _ = write!(
                        summary,
                        "pending_checkpoints={} ",
                        incomplete_checkpoints.join(", ")
                    );
                }
    
                if summary.trim().is_empty() {
                    summary = "no recorded outcomes".to_string();
                }
    
                let failure_reason = if !required_failed.is_empty() {
                    Some(format!(
                        "Required checks failed: {}",
                        required_failed.join(", ")
                    ))
                } else if !optional_failed.is_empty() {
                    Some(format!(
                        "Optional checks failed: {}",
                        optional_failed.join(", ")
                    ))
                } else if !incomplete_checkpoints.is_empty() {
                    Some(format!(
                        "Checkpoints incomplete: {}",
                        incomplete_checkpoints.join(", ")
                    ))
                } else if let Some(ec) = exit_code {
                    if ec != 0 {
                        Some(format!("Runtime exited with code {ec}"))
                    } else {
                        None
                    }
                } else if terminated_reason.is_some() {
                    Some("Runtime terminated".to_string())
                } else {
                    None
                };
    
                prior_attempts.push(AttemptSummary {
                    attempt_number: prior.attempt_number,
                    summary: summary.trim().to_string(),
                    failure_reason,
                });
            }
    
            let latest = attempts.last();
            let mut required_failures: Vec<String> = Vec::new();
            let mut optional_failures: Vec<String> = Vec::new();
            let mut incomplete_checkpoints: Vec<String> = Vec::new();
            let mut exit_code: Option<i32> = None;
            #[allow(clippy::useless_let_if_seq, clippy::option_if_let_else)]
            let terminated_reason = if let Some(last) = latest {
                required_failures = last
                    .check_results
                    .iter()
                    .filter(|r| r.required && !r.passed)
                    .map(|r| r.name.clone())
                    .collect();
                optional_failures = last
                    .check_results
                    .iter()
                    .filter(|r| !r.required && !r.passed)
                    .map(|r| r.name.clone())
                    .collect();
                incomplete_checkpoints = last
                    .checkpoints
                    .iter()
                    .filter(|cp| cp.state != AttemptCheckpointState::Completed)
                    .map(|cp| cp.checkpoint_id.clone())
                    .collect();
    
                let (ec, term) = self
                    .attempt_runtime_outcome(last.id)
                    .unwrap_or((None, None));
                exit_code = ec;
                term
            } else {
                None
            };
    
            #[allow(clippy::items_after_statements)]
            fn truncate(s: &str, max_len: usize) -> String {
                if s.len() <= max_len {
                    return s.to_string();
                }
                s.chars().take(max_len).collect()
            }
    
            let mut ctx = String::new();
            let _ = writeln!(
                ctx,
                "Retry attempt {attempt_number}/{max_attempts} for task {task_id}"
            );
    
            if let Some(last) = latest {
                let _ = writeln!(ctx, "Previous attempt: {}", last.id);
    
                if !required_failures.is_empty() {
                    let _ = writeln!(
                        ctx,
                        "Required check failures (must fix): {}",
                        required_failures.join(", ")
                    );
                    for r in last
                        .check_results
                        .iter()
                        .filter(|r| r.required && !r.passed)
                    {
                        let _ = writeln!(ctx, "--- Check: {}", r.name);
                        let _ = writeln!(ctx, "exit_code={}", r.exit_code);
                        let _ = writeln!(ctx, "output:\n{}", truncate(&r.output, 2000));
                    }
                }
    
                if !optional_failures.is_empty() {
                    let _ = writeln!(
                        ctx,
                        "Optional check failures: {}",
                        optional_failures.join(", ")
                    );
                }
    
                if let Some(ec) = exit_code {
                    let _ = writeln!(ctx, "Runtime exit code: {ec}");
                }
                if let Some(ref reason) = terminated_reason {
                    let _ = writeln!(ctx, "Runtime terminated: {reason}");
                }
                if !incomplete_checkpoints.is_empty() {
                    let _ = writeln!(
                        ctx,
                        "Incomplete checkpoints from prior attempt: {}",
                        incomplete_checkpoints.join(", ")
                    );
                }
    
                if let Some(diff_id) = last.diff_id {
                    if let Ok(artifact) = self.read_diff_artifact(diff_id) {
                        let created: Vec<String> = artifact
                            .diff
                            .changes
                            .iter()
                            .filter(|c| c.change_type == ChangeType::Created)
                            .map(|c| c.path.to_string_lossy().to_string())
                            .collect();
                        let modified: Vec<String> = artifact
                            .diff
                            .changes
                            .iter()
                            .filter(|c| c.change_type == ChangeType::Modified)
                            .map(|c| c.path.to_string_lossy().to_string())
                            .collect();
                        let deleted: Vec<String> = artifact
                            .diff
                            .changes
                            .iter()
                            .filter(|c| c.change_type == ChangeType::Deleted)
                            .map(|c| c.path.to_string_lossy().to_string())
                            .collect();
    
                        let _ = writeln!(
                            ctx,
                            "Filesystem changes observed (from diff): change_count={} created={} modified={} deleted={}",
                            artifact.diff.change_count(),
                            created.len(),
                            modified.len(),
                            deleted.len()
                        );
                        if !created.is_empty() {
                            let _ = writeln!(ctx, "Created:\n{}", created.join("\n"));
                        }
                        if !modified.is_empty() {
                            let _ = writeln!(ctx, "Modified:\n{}", modified.join("\n"));
                        }
                        if !deleted.is_empty() {
                            let _ = writeln!(ctx, "Deleted:\n{}", deleted.join("\n"));
                        }
                    }
                }
            }
    
            Ok((
                ctx,
                prior_attempts,
                prior_attempt_ids,
                required_failures,
                optional_failures,
                exit_code,
                terminated_reason,
            ))
        }

            #[allow(clippy::items_after_statements)]
            fn truncate(s: &str, max_len: usize) -> String {
                if s.len() <= max_len {
                    return s.to_string();
                }
                s.chars().take(max_len).collect()
            }

    
        fn flow_for_task(state: &AppState, task_id: Uuid, origin: &'static str) -> Result<TaskFlow> {
            state
                .flows
                .values()
                .filter(|f| f.task_executions.contains_key(&task_id))
                .max_by_key(|f| (f.updated_at, f.id))
                .cloned()
                .ok_or_else(|| {
                    HivemindError::user("task_not_in_flow", "Task is not part of any flow", origin)
                })
        }

    
        fn inspect_task_worktree(
            flow: &TaskFlow,
            state: &AppState,
            task_id: Uuid,
            origin: &'static str,
        ) -> Result<WorktreeStatus> {
            let manager = Self::worktree_manager_for_flow(flow, state)?;
            let status = manager
                .inspect(flow.id, task_id)
                .map_err(|e| Self::worktree_error_to_hivemind(e, origin))?;
            if !status.is_worktree {
                return Err(HivemindError::user(
                    "worktree_not_found",
                    "Worktree not found for task",
                    origin,
                ));
            }
            Ok(status)
        }

    
        fn resolve_latest_attempt_without_diff(
            state: &AppState,
            flow_id: Uuid,
            task_id: Uuid,
            origin: &'static str,
        ) -> Result<AttemptState> {
            state
                .attempts
                .values()
                .filter(|a| a.flow_id == flow_id && a.task_id == task_id)
                .filter(|a| a.diff_id.is_none())
                .max_by_key(|a| a.started_at)
                .cloned()
                .ok_or_else(|| {
                    HivemindError::system(
                        "attempt_not_found",
                        "Attempt not found for running task",
                        origin,
                    )
                })
        }

    
        fn normalized_checkpoint_ids(raw: &[String]) -> Vec<String> {
            let mut ids = Vec::new();
            let mut seen = HashSet::new();
    
            for candidate in raw {
                let trimmed = candidate.trim();
                if trimmed.is_empty() {
                    continue;
                }
                if seen.insert(trimmed.to_string()) {
                    ids.push(trimmed.to_string());
                }
            }
    
            if ids.is_empty() {
                ids.push("checkpoint-1".to_string());
            }
    
            ids
        }

    
        fn checkpoint_order(checkpoint_ids: &[String], checkpoint_id: &str) -> Option<(u32, u32)> {
            let idx = checkpoint_ids.iter().position(|id| id == checkpoint_id)?;
            let order = u32::try_from(idx.saturating_add(1)).ok()?;
            let total = u32::try_from(checkpoint_ids.len()).ok()?;
            Some((order, total))
        }

    
        fn fail_running_attempt(
            &self,
            flow: &TaskFlow,
            task_id: Uuid,
            attempt_id: Uuid,
            reason: &str,
            origin: &'static str,
        ) -> Result<()> {
            let corr_task =
                CorrelationIds::for_graph_flow_task(flow.project_id, flow.graph_id, flow.id, task_id);
            let corr_attempt = CorrelationIds::for_graph_flow_task_attempt(
                flow.project_id,
                flow.graph_id,
                flow.id,
                task_id,
                attempt_id,
            );
    
            self.append_event(
                Event::new(
                    EventPayload::TaskExecutionStateChanged {
                        flow_id: flow.id,
                        task_id,
                        attempt_id: Some(attempt_id),
                        from: TaskExecState::Running,
                        to: TaskExecState::Failed,
                    },
                    corr_task,
                ),
                origin,
            )?;
    
            self.append_event(
                Event::new(
                    EventPayload::TaskExecutionFailed {
                        flow_id: flow.id,
                        task_id,
                        attempt_id: Some(attempt_id),
                        reason: Some(reason.to_string()),
                    },
                    corr_attempt,
                ),
                origin,
            )
        }

    
        fn resolve_latest_attempt_with_diff(
            state: &AppState,
            flow_id: Uuid,
            task_id: Uuid,
            origin: &'static str,
        ) -> Result<AttemptState> {
            state
                .attempts
                .values()
                .filter(|a| a.flow_id == flow_id && a.task_id == task_id)
                .filter(|a| a.diff_id.is_some())
                .max_by_key(|a| a.started_at)
                .cloned()
                .ok_or_else(|| {
                    HivemindError::system(
                        "attempt_not_found",
                        "Attempt not found for verifying task",
                        origin,
                    )
                })
        }

        #[allow(clippy::too_many_lines)]
        fn process_verifying_task(&self, flow_id: &str, task_id: Uuid) -> Result<TaskFlow> {
            let flow = self.get_flow(flow_id)?;
            if flow.state != FlowState::Running {
                return Ok(flow);
            }
    
            let state = self.state()?;
            let graph = state.graphs.get(&flow.graph_id).ok_or_else(|| {
                HivemindError::system("graph_not_found", "Graph not found", "registry:tick_flow")
            })?;
    
            let origin = "registry:tick_flow";
            let exec = flow.task_executions.get(&task_id).ok_or_else(|| {
                HivemindError::system("task_exec_not_found", "Task execution not found", origin)
            })?;
            if exec.state != TaskExecState::Verifying {
                return Ok(flow);
            }
    
            let attempt = Self::resolve_latest_attempt_with_diff(&state, flow.id, task_id, origin)?;
            let diff_id = attempt.diff_id.ok_or_else(|| {
                HivemindError::system("diff_not_found", "Diff not found for attempt", origin)
            })?;
            let artifact = self.read_diff_artifact(diff_id)?;
    
            let baseline_id = attempt.baseline_id.ok_or_else(|| {
                HivemindError::system(
                    "baseline_not_found",
                    "Baseline not found for attempt",
                    origin,
                )
            })?;
            let baseline = self.read_baseline_artifact(baseline_id)?;
    
            let worktree_status = Self::inspect_task_worktree(&flow, &state, task_id, origin)?;
    
            let task = graph.tasks.get(&task_id).ok_or_else(|| {
                HivemindError::system("task_not_found", "Task not found in graph", origin)
            })?;
    
            let mut verification = if let Some(scope) = &task.scope {
                let (commits_created, branches_created) =
                    Self::detect_git_operations(&worktree_status.path, &baseline, attempt.id);
    
                ScopeEnforcer::new(scope.clone()).verify_all(
                    &artifact.diff,
                    commits_created,
                    branches_created,
                    task_id,
                    attempt.id,
                )
            } else {
                VerificationResult::pass(task_id, attempt.id)
            };
    
            if let Some(scope) = &task.scope {
                let repo_violations =
                    Self::verify_repository_scope(scope, &flow, &state, task_id, origin);
                if !repo_violations.is_empty() {
                    verification.passed = false;
                    verification.violations.extend(repo_violations);
                }
    
                let ambient_violations =
                    self.verify_scope_environment_baseline(&flow, &state, task_id, attempt.id, origin);
                if !ambient_violations.is_empty() {
                    verification.passed = false;
                    verification.violations.extend(ambient_violations);
                }
    
                let traced_violations =
                    self.verify_scope_trace_writes(&flow, &state, task_id, attempt.id, origin);
                if !traced_violations.is_empty() {
                    verification.passed = false;
                    verification.violations.extend(traced_violations);
                }
            }
    
            let corr_task =
                CorrelationIds::for_graph_flow_task(flow.project_id, flow.graph_id, flow.id, task_id);
    
            if !verification.passed {
                if let Some(scope) = &task.scope {
                    self.append_event(
                        Event::new(
                            EventPayload::ScopeViolationDetected {
                                flow_id: flow.id,
                                task_id,
                                attempt_id: attempt.id,
                                verification_id: verification.id,
                                verified_at: verification.verified_at,
                                scope: scope.clone(),
                                violations: verification.violations.clone(),
                            },
                            CorrelationIds::for_graph_flow_task_attempt(
                                flow.project_id,
                                flow.graph_id,
                                flow.id,
                                task_id,
                                attempt.id,
                            ),
                        ),
                        origin,
                    )?;
                }
    
                self.append_event(
                    Event::new(
                        EventPayload::TaskExecutionStateChanged {
                            flow_id: flow.id,
                            task_id,
                            attempt_id: Some(attempt.id),
                            from: TaskExecState::Verifying,
                            to: TaskExecState::Failed,
                        },
                        corr_task,
                    ),
                    origin,
                )?;
    
                self.append_event(
                    Event::new(
                        EventPayload::TaskExecutionFailed {
                            flow_id: flow.id,
                            task_id,
                            attempt_id: Some(attempt.id),
                            reason: Some("scope_violation".to_string()),
                        },
                        CorrelationIds::for_graph_flow_task_attempt(
                            flow.project_id,
                            flow.graph_id,
                            flow.id,
                            task_id,
                            attempt.id,
                        ),
                    ),
                    origin,
                )?;
    
                let violations = verification
                    .violations
                    .iter()
                    .map(|v| {
                        let path = v.path.as_deref().unwrap_or("-");
                        format!("{:?}: {path}: {}", v.violation_type, v.description)
                    })
                    .collect::<Vec<_>>()
                    .join("\n");
    
                return Err(HivemindError::scope(
                    "scope_violation",
                    format!("Scope violation detected:\n{violations}"),
                    origin,
                )
                .with_hint(format!(
                    "Worktree preserved at {}",
                    worktree_status.path.display()
                )));
            }
    
            let corr_attempt = CorrelationIds::for_graph_flow_task_attempt(
                flow.project_id,
                flow.graph_id,
                flow.id,
                task_id,
                attempt.id,
            );
    
            if let Some(scope) = &task.scope {
                self.append_event(
                    Event::new(
                        EventPayload::ScopeValidated {
                            flow_id: flow.id,
                            task_id,
                            attempt_id: attempt.id,
                            verification_id: verification.id,
                            verified_at: verification.verified_at,
                            scope: scope.clone(),
                        },
                        corr_attempt.clone(),
                    ),
                    origin,
                )?;
            }
    
            let target_dir = self
                .config
                .data_dir
                .join("cargo-target")
                .join(flow.id.to_string())
                .join(task_id.to_string())
                .join(attempt.id.to_string())
                .join("checks");
            let _ = fs::create_dir_all(&target_dir);
    
            let mut results = Vec::new();
            for check in &task.criteria.checks {
                self.append_event(
                    Event::new(
                        EventPayload::CheckStarted {
                            flow_id: flow.id,
                            task_id,
                            attempt_id: attempt.id,
                            check_name: check.name.clone(),
                            required: check.required,
                        },
                        corr_attempt.clone(),
                    ),
                    origin,
                )?;
    
                let started = Instant::now();
                let (exit_code, combined) = match Self::run_check_command(
                    &worktree_status.path,
                    &target_dir,
                    &check.command,
                    check.timeout_ms,
                ) {
                    Ok((exit_code, output, _timed_out)) => (exit_code, output),
                    Err(e) => (127, e.to_string()),
                };
                let duration_ms =
                    u64::try_from(started.elapsed().as_millis().min(u128::from(u64::MAX)))
                        .unwrap_or(u64::MAX);
                let passed = exit_code == 0;
    
                self.append_event(
                    Event::new(
                        EventPayload::CheckCompleted {
                            flow_id: flow.id,
                            task_id,
                            attempt_id: attempt.id,
                            check_name: check.name.clone(),
                            passed,
                            exit_code,
                            output: combined.clone(),
                            duration_ms,
                            required: check.required,
                        },
                        corr_attempt.clone(),
                    ),
                    origin,
                )?;
    
                results.push((check.name.clone(), check.required, passed));
            }
    
            let required_failed = results
                .iter()
                .any(|(_, required, passed)| *required && !*passed);
    
            if !required_failed {
                self.append_event(
                    Event::new(
                        EventPayload::TaskExecutionStateChanged {
                            flow_id: flow.id,
                            task_id,
                            attempt_id: Some(attempt.id),
                            from: TaskExecState::Verifying,
                            to: TaskExecState::Success,
                        },
                        corr_task,
                    ),
                    origin,
                )?;
    
                self.append_event(
                    Event::new(
                        EventPayload::TaskExecutionSucceeded {
                            flow_id: flow.id,
                            task_id,
                            attempt_id: Some(attempt.id),
                        },
                        corr_attempt,
                    ),
                    origin,
                )?;
    
                let frozen_commit_sha = Self::resolve_task_frozen_commit_sha(&flow, &state, task_id);
                self.emit_task_execution_frozen(&flow, task_id, frozen_commit_sha, origin)?;
    
                if let Ok(managers) =
                    Self::worktree_managers_for_flow(&flow, &state, "registry:tick_flow")
                {
                    for (_repo_name, manager) in managers {
                        if manager.config().cleanup_on_success {
                            if let Ok(status) = manager.inspect(flow.id, task_id) {
                                if status.is_worktree {
                                    let _ = manager.remove(&status.path);
                                }
                            }
                        }
                    }
                }
    
                let updated = self.get_flow(flow_id)?;
                let all_success = updated
                    .task_executions
                    .values()
                    .all(|e| e.state == TaskExecState::Success);
                if all_success {
                    let event = Event::new(
                        EventPayload::TaskFlowCompleted {
                            flow_id: updated.id,
                        },
                        CorrelationIds::for_graph_flow(
                            updated.project_id,
                            updated.graph_id,
                            updated.id,
                        ),
                    );
                    self.append_event(event, origin)?;
                    self.maybe_autostart_dependent_flows(updated.id)?;
                }
    
                return self.get_flow(flow_id);
            }
    
            let max_retries = task.retry_policy.max_retries;
            let max_attempts = max_retries.saturating_add(1);
            let can_retry = exec.attempt_count < max_attempts;
            let to = if can_retry {
                TaskExecState::Retry
            } else {
                TaskExecState::Failed
            };
    
            self.append_event(
                Event::new(
                    EventPayload::TaskExecutionStateChanged {
                        flow_id: flow.id,
                        task_id,
                        attempt_id: Some(attempt.id),
                        from: TaskExecState::Verifying,
                        to,
                    },
                    corr_task,
                ),
                origin,
            )?;
    
            if matches!(to, TaskExecState::Retry | TaskExecState::Failed) {
                self.append_event(
                    Event::new(
                        EventPayload::TaskExecutionFailed {
                            flow_id: flow.id,
                            task_id,
                            attempt_id: Some(attempt.id),
                            reason: Some("required_checks_failed".to_string()),
                        },
                        corr_attempt.clone(),
                    ),
                    origin,
                )?;
            }
    
            let failures = results
                .into_iter()
                .filter(|(_, required, passed)| *required && !*passed)
                .map(|(name, _, _)| name)
                .collect::<Vec<_>>()
                .join(", ");
    
            let err = HivemindError::verification(
                "required_checks_failed",
                format!("Required checks failed: {failures}"),
                origin,
            )
            .with_hint(format!(
                "View check outputs via `hivemind verify results {}`. Worktree preserved at {}",
                attempt.id,
                worktree_status.path.display()
            ));
    
            self.record_error_event(&err, corr_attempt);
    
            Err(err)
        }

    
        pub fn verify_run(&self, task_id: &str) -> Result<TaskFlow> {
            let origin = "registry:verify_run";
            let id = Uuid::parse_str(task_id).map_err(|_| {
                HivemindError::user(
                    "invalid_task_id",
                    format!("'{task_id}' is not a valid task ID"),
                    origin,
                )
            })?;
    
            let state = self.state()?;
            let flow = Self::flow_for_task(&state, id, origin)?;
            let exec = flow.task_executions.get(&id).ok_or_else(|| {
                HivemindError::system("task_exec_not_found", "Task execution not found", origin)
            })?;
            if exec.state != TaskExecState::Verifying {
                return Err(HivemindError::user(
                    "task_not_verifying",
                    "Task is not in verifying state",
                    origin,
                )
                .with_hint(
                    "Complete the task execution first, or run `hivemind flow tick <flow-id>`",
                ));
            }
    
            self.process_verifying_task(&flow.id.to_string(), id)
        }

    
        fn run_check_command(
            workdir: &Path,
            cargo_target_dir: &Path,
            command: &str,
            timeout_ms: Option<u64>,
        ) -> std::io::Result<(i32, String, bool)> {
            let started = Instant::now();
    
            let mut cmd = std::process::Command::new("sh");
            cmd.current_dir(workdir)
                .env("CARGO_TARGET_DIR", cargo_target_dir)
                .args(["-lc", command]);
    
            if let Some(timeout_ms) = timeout_ms {
                let mut child = cmd.stdout(Stdio::piped()).stderr(Stdio::piped()).spawn()?;
    
                let mut out_buf = Vec::new();
                let mut err_buf = Vec::new();
    
                let stdout = child.stdout.take();
                let stderr = child.stderr.take();
    
                let out_handle = std::thread::spawn(move || {
                    if let Some(mut stdout) = stdout {
                        let _ = stdout.read_to_end(&mut out_buf);
                    }
                    out_buf
                });
                let err_handle = std::thread::spawn(move || {
                    if let Some(mut stderr) = stderr {
                        let _ = stderr.read_to_end(&mut err_buf);
                    }
                    err_buf
                });
    
                let timeout = Duration::from_millis(timeout_ms);
                let mut timed_out = false;
                let status = loop {
                    if let Some(status) = child.try_wait()? {
                        break status;
                    }
                    if started.elapsed() >= timeout {
                        timed_out = true;
                        let _ = child.kill();
                        break child.wait()?;
                    }
                    std::thread::sleep(Duration::from_millis(10));
                };
    
                let stdout_buf = out_handle.join().unwrap_or_default();
                let stderr_buf = err_handle.join().unwrap_or_default();
    
                let mut combined = String::new();
                if timed_out {
                    let _ = writeln!(combined, "timed out after {timeout_ms}ms");
                }
                combined.push_str(&String::from_utf8_lossy(&stdout_buf));
                if !combined.ends_with('\n') {
                    combined.push('\n');
                }
                combined.push_str(&String::from_utf8_lossy(&stderr_buf));
    
                let exit_code = if timed_out {
                    124
                } else {
                    status.code().unwrap_or(-1)
                };
    
                return Ok((exit_code, combined, timed_out));
            }
    
            let out = cmd.output()?;
            let mut combined = String::new();
            combined.push_str(&String::from_utf8_lossy(&out.stdout));
            if !combined.ends_with('\n') {
                combined.push('\n');
            }
            combined.push_str(&String::from_utf8_lossy(&out.stderr));
            Ok((out.status.code().unwrap_or(-1), combined, false))
        }

    
        fn verify_repository_scope(
            scope: &Scope,
            flow: &TaskFlow,
            state: &AppState,
            task_id: Uuid,
            origin: &'static str,
        ) -> Vec<crate::core::enforcement::ScopeViolation> {
            if scope.repositories.is_empty() {
                return Vec::new();
            }
    
            let Ok(worktrees) = Self::inspect_task_worktrees(flow, state, task_id, origin) else {
                return vec![crate::core::enforcement::ScopeViolation::filesystem(
                    "<worktree>",
                    "Repository scope verification failed: worktree missing",
                )];
            };
    
            let mut violations = Vec::new();
            for (repo_name, status) in worktrees {
                let changed_paths = Self::parse_git_status_paths(&status.path);
                if changed_paths.is_empty() {
                    continue;
                }
    
                let allowed_mode = scope
                    .repositories
                    .iter()
                    .find(|r| r.repo == repo_name || r.repo == status.path.to_string_lossy())
                    .map(|r| r.mode);
    
                match allowed_mode {
                    Some(RepoAccessMode::ReadWrite) => {}
                    Some(RepoAccessMode::ReadOnly) => {
                        violations.push(crate::core::enforcement::ScopeViolation::filesystem(
                            format!("{repo_name}/{}", changed_paths[0]),
                            format!("Repository '{repo_name}' is read-only in scope"),
                        ));
                    }
                    None => {
                        violations.push(crate::core::enforcement::ScopeViolation::filesystem(
                            format!("{repo_name}/{}", changed_paths[0]),
                            format!("Repository '{repo_name}' is not declared in task scope"),
                        ));
                    }
                }
            }
            violations
        }

    
        fn verify_scope_environment_baseline(
            &self,
            flow: &TaskFlow,
            state: &AppState,
            task_id: Uuid,
            attempt_id: Uuid,
            origin: &'static str,
        ) -> Vec<crate::core::enforcement::ScopeViolation> {
            let Ok(baseline) = self.read_scope_baseline_artifact(attempt_id) else {
                return Vec::new();
            };
            let Ok(worktrees) = Self::inspect_task_worktrees(flow, state, task_id, origin) else {
                return Vec::new();
            };
            let allowed_roots: Vec<PathBuf> = worktrees
                .iter()
                .filter_map(|(_, status)| status.path.canonicalize().ok())
                .collect();
    
            let mut violations = Vec::new();
            for snapshot in &baseline.repo_snapshots {
                let repo_path = Path::new(&snapshot.repo_path);
                let current_head = Self::repo_git_head(repo_path);
                if current_head != snapshot.git_head {
                    violations.push(crate::core::enforcement::ScopeViolation::git(format!(
                        "Repository HEAD changed outside task worktree (before: {:?}, after: {:?})",
                        snapshot.git_head, current_head
                    )));
                }
    
                let current_status = Self::repo_status_lines(repo_path);
                if current_status != snapshot.status_lines {
                    let path_preview = current_status
                        .first()
                        .and_then(|line| line.strip_prefix("?? ").or_else(|| line.get(3..)))
                        .map_or("<unknown>", str::trim);
                    violations.push(crate::core::enforcement::ScopeViolation::filesystem(
                        format!("{}:{path_preview}", snapshot.repo_path),
                        "Repository workspace changed outside task worktree",
                    ));
                }
            }
    
            let current_tmp = Self::list_tmp_entries();
            let baseline_tmp: HashSet<String> = baseline.tmp_entries.into_iter().collect();
            for created in current_tmp
                .into_iter()
                .filter(|name| !baseline_tmp.contains(name))
                .take(32)
            {
                let path = PathBuf::from("/tmp").join(&created);
                let canonical = path.canonicalize().unwrap_or(path);
                if allowed_roots.iter().any(|root| canonical.starts_with(root)) {
                    continue;
                }
                if Self::scope_trace_is_ignored(&canonical, None, &self.config.data_dir) {
                    continue;
                }
                violations.push(crate::core::enforcement::ScopeViolation::filesystem(
                    canonical.to_string_lossy().to_string(),
                    "Filesystem write outside task worktree detected in /tmp",
                ));
            }
    
            violations
        }

    
        fn verify_scope_trace_writes(
            &self,
            flow: &TaskFlow,
            state: &AppState,
            task_id: Uuid,
            attempt_id: Uuid,
            origin: &'static str,
        ) -> Vec<crate::core::enforcement::ScopeViolation> {
            let trace_path = self.scope_trace_path(attempt_id);
            let Ok(contents) = fs::read_to_string(&trace_path) else {
                return Vec::new();
            };
    
            let Ok(worktrees) = Self::inspect_task_worktrees(flow, state, task_id, origin) else {
                return Vec::new();
            };
            let allowed_roots: Vec<PathBuf> = worktrees
                .iter()
                .filter_map(|(_, status)| status.path.canonicalize().ok())
                .collect();
            let home_dir = env::var("HOME").ok().map(PathBuf::from);
    
            let mut violations = Vec::new();
            for observed in Self::parse_scope_trace_written_paths(&contents) {
                let observed_abs = if observed.is_absolute() {
                    observed
                } else if let Some((_, first)) = worktrees.first() {
                    first.path.join(observed)
                } else {
                    continue;
                };
    
                let canonical = observed_abs
                    .canonicalize()
                    .unwrap_or_else(|_| observed_abs.clone());
                if Self::scope_trace_is_ignored(&canonical, home_dir.as_deref(), &self.config.data_dir)
                {
                    continue;
                }
                if allowed_roots.iter().any(|root| canonical.starts_with(root)) {
                    continue;
                }
    
                violations.push(crate::core::enforcement::ScopeViolation::filesystem(
                    canonical.to_string_lossy().to_string(),
                    "Write outside task worktree detected via runtime syscall trace",
                ));
            }
    
            violations.sort_by(|a, b| a.path.cmp(&b.path));
            violations.dedup_by(|a, b| a.path == b.path);
            violations
        }

    
        fn emit_task_execution_completion_events(
            &self,
            flow: &TaskFlow,
            task_id: Uuid,
            attempt: &AttemptState,
            completion: CompletionArtifacts<'_>,
            origin: &'static str,
        ) -> Result<()> {
            let corr_task =
                CorrelationIds::for_graph_flow_task(flow.project_id, flow.graph_id, flow.id, task_id);
            let corr_attempt = CorrelationIds::for_graph_flow_task_attempt(
                flow.project_id,
                flow.graph_id,
                flow.id,
                task_id,
                attempt.id,
            );
    
            self.append_event(
                Event::new(
                    EventPayload::TaskExecutionStateChanged {
                        flow_id: flow.id,
                        task_id,
                        attempt_id: Some(attempt.id),
                        from: TaskExecState::Running,
                        to: TaskExecState::Verifying,
                    },
                    corr_task,
                ),
                origin,
            )?;
    
            if let Some(commit_sha) = completion.checkpoint_commit_sha {
                self.append_event(
                    Event::new(
                        EventPayload::CheckpointCommitCreated {
                            flow_id: flow.id,
                            task_id,
                            attempt_id: attempt.id,
                            commit_sha,
                        },
                        corr_attempt.clone(),
                    ),
                    origin,
                )?;
            }
    
            for change in &completion.artifact.diff.changes {
                self.append_event(
                    Event::new(
                        EventPayload::FileModified {
                            flow_id: flow.id,
                            task_id,
                            attempt_id: attempt.id,
                            path: change.path.to_string_lossy().to_string(),
                            change_type: change.change_type,
                            old_hash: change.old_hash.clone(),
                            new_hash: change.new_hash.clone(),
                        },
                        corr_attempt.clone(),
                    ),
                    origin,
                )?;
            }
    
            self.append_event(
                Event::new(
                    EventPayload::DiffComputed {
                        flow_id: flow.id,
                        task_id,
                        attempt_id: attempt.id,
                        diff_id: completion.artifact.diff.id,
                        baseline_id: completion.baseline_id,
                        change_count: completion.artifact.diff.change_count(),
                    },
                    corr_attempt,
                ),
                origin,
            )?;
    
            Ok(())
        }

    
        fn capture_and_store_baseline(
            &self,
            worktree_path: &Path,
            origin: &'static str,
        ) -> Result<Baseline> {
            let baseline = Baseline::capture(worktree_path)
                .map_err(|e| HivemindError::system("baseline_capture_failed", e.to_string(), origin))?;
            self.write_baseline_artifact(&baseline)?;
            Ok(baseline)
        }

    
        fn compute_and_store_diff(
            &self,
            baseline_id: Uuid,
            worktree_path: &Path,
            task_id: Uuid,
            attempt_id: Uuid,
            origin: &'static str,
        ) -> Result<DiffArtifact> {
            let baseline = self.read_baseline_artifact(baseline_id)?;
            let diff = Diff::compute(&baseline, worktree_path)
                .map_err(|e| HivemindError::system("diff_compute_failed", e.to_string(), origin))?
                .for_task(task_id)
                .for_attempt(attempt_id);
    
            let mut unified = String::new();
            for change in &diff.changes {
                if let Ok(chunk) = self.unified_diff_for_change(baseline_id, worktree_path, change) {
                    unified.push_str(&chunk);
                    if !chunk.ends_with('\n') {
                        unified.push('\n');
                    }
                }
            }
    
            let artifact = DiffArtifact { diff, unified };
            self.write_diff_artifact(&artifact)?;
            Ok(artifact)
        }

    
        fn git_ref_exists(repo_path: &Path, reference: &str) -> bool {
            std::process::Command::new("git")
                .current_dir(repo_path)
                .args(["show-ref", "--verify", "--quiet", reference])
                .status()
                .map(|status| status.success())
                .unwrap_or(false)
        }

    
        fn default_base_ref_for_repo(
            flow: &TaskFlow,
            manager: &WorktreeManager,
            is_primary: bool,
        ) -> String {
            let flow_ref = format!("refs/heads/flow/{}", flow.id);
            if Self::git_ref_exists(manager.repo_path(), &flow_ref) {
                return format!("flow/{}", flow.id);
            }
            if is_primary {
                return flow
                    .base_revision
                    .clone()
                    .unwrap_or_else(|| "HEAD".to_string());
            }
            "HEAD".to_string()
        }

    
        fn ensure_task_worktree_status(
            manager: &WorktreeManager,
            flow: &TaskFlow,
            task_id: Uuid,
            base_ref: &str,
            origin: &'static str,
        ) -> Result<WorktreeStatus> {
            let status = manager
                .inspect(flow.id, task_id)
                .map_err(|e| Self::worktree_error_to_hivemind(e, origin))?;
            if status.is_worktree {
                return Ok(status);
            }
    
            manager
                .create(flow.id, task_id, Some(base_ref))
                .map_err(|e| Self::worktree_error_to_hivemind(e, origin))?;
            let status = manager
                .inspect(flow.id, task_id)
                .map_err(|e| Self::worktree_error_to_hivemind(e, origin))?;
            if !status.is_worktree {
                return Err(HivemindError::git(
                    "worktree_create_failed",
                    format!(
                        "Worktree path exists but is not a git worktree: {}",
                        status.path.display()
                    ),
                    origin,
                ));
            }
            Ok(status)
        }

    
        fn ensure_task_worktree(
            flow: &TaskFlow,
            state: &AppState,
            task_id: Uuid,
            origin: &'static str,
        ) -> Result<WorktreeStatus> {
            let managers = Self::worktree_managers_for_flow(flow, state, origin)?;
            let mut primary_status: Option<WorktreeStatus> = None;
            for (idx, (_repo_name, manager)) in managers.iter().enumerate() {
                let base_ref = Self::default_base_ref_for_repo(flow, manager, idx == 0);
                let status =
                    Self::ensure_task_worktree_status(manager, flow, task_id, &base_ref, origin)?;
                if idx == 0 {
                    primary_status = Some(status);
                }
            }
            primary_status.ok_or_else(|| {
                HivemindError::user(
                    "project_has_no_repo",
                    "Project has no repository attached",
                    origin,
                )
            })
        }

    
        fn inspect_task_worktrees(
            flow: &TaskFlow,
            state: &AppState,
            task_id: Uuid,
            origin: &'static str,
        ) -> Result<Vec<(String, WorktreeStatus)>> {
            let managers = Self::worktree_managers_for_flow(flow, state, origin)?;
            let mut statuses = Vec::new();
            for (repo_name, manager) in managers {
                let status = manager
                    .inspect(flow.id, task_id)
                    .map_err(|e| Self::worktree_error_to_hivemind(e, origin))?;
                if !status.is_worktree {
                    return Err(HivemindError::user(
                        "worktree_not_found",
                        format!("Worktree not found for task in repo '{repo_name}'"),
                        origin,
                    ));
                }
                statuses.push((repo_name, status));
            }
            Ok(statuses)
        }

}
