//! Auto-generated registry split module: governance.
//!
//! Generated by scripts/registry_split_migrator.py.

use crate::core::registry::shared_prelude::*;
use crate::core::registry::shared_types::*;
use crate::core::registry::*;

impl Registry {
    
        fn governance_projects_dir(&self) -> PathBuf {
            self.config.data_dir.join("projects")
        }

    
        fn governance_project_root(&self, project_id: Uuid) -> PathBuf {
            self.governance_projects_dir().join(project_id.to_string())
        }

    
        pub fn governance_global_root(&self) -> PathBuf {
            self.config.data_dir.join("global")
        }

    
        fn governance_artifact_locations(&self, project_id: Uuid) -> Vec<GovernanceArtifactLocation> {
            let project_root = self.governance_project_root(project_id);
            let global_root = self.governance_global_root();
            vec![
                GovernanceArtifactLocation {
                    project_id: Some(project_id),
                    scope: "project",
                    artifact_kind: "constitution",
                    artifact_key: "constitution.yaml".to_string(),
                    is_dir: false,
                    path: project_root.join("constitution.yaml"),
                },
                GovernanceArtifactLocation {
                    project_id: Some(project_id),
                    scope: "project",
                    artifact_kind: "documents",
                    artifact_key: "documents".to_string(),
                    is_dir: true,
                    path: project_root.join("documents"),
                },
                GovernanceArtifactLocation {
                    project_id: Some(project_id),
                    scope: "project",
                    artifact_kind: "notepad",
                    artifact_key: "notepad.md".to_string(),
                    is_dir: false,
                    path: project_root.join("notepad.md"),
                },
                GovernanceArtifactLocation {
                    project_id: Some(project_id),
                    scope: "project",
                    artifact_kind: "graph_snapshot",
                    artifact_key: "graph_snapshot.json".to_string(),
                    is_dir: false,
                    path: project_root.join("graph_snapshot.json"),
                },
                GovernanceArtifactLocation {
                    project_id: None,
                    scope: "global",
                    artifact_kind: "skills",
                    artifact_key: "skills".to_string(),
                    is_dir: true,
                    path: global_root.join("skills"),
                },
                GovernanceArtifactLocation {
                    project_id: None,
                    scope: "global",
                    artifact_kind: "system_prompts",
                    artifact_key: "system_prompts".to_string(),
                    is_dir: true,
                    path: global_root.join("system_prompts"),
                },
                GovernanceArtifactLocation {
                    project_id: None,
                    scope: "global",
                    artifact_kind: "templates",
                    artifact_key: "templates".to_string(),
                    is_dir: true,
                    path: global_root.join("templates"),
                },
                GovernanceArtifactLocation {
                    project_id: None,
                    scope: "global",
                    artifact_kind: "notepad",
                    artifact_key: "notepad.md".to_string(),
                    is_dir: false,
                    path: global_root.join("notepad.md"),
                },
            ]
        }

    
        fn governance_default_file_contents(location: &GovernanceArtifactLocation) -> &'static [u8] {
            match (location.scope, location.artifact_kind) {
                ("project", "constitution") => b"version: 1\nschema_version: constitution.v1\ncompatibility:\n  minimum_hivemind_version: 0.1.32\n  governance_schema_version: governance.v1\npartitions: []\nrules: []\n",
                ("project", "graph_snapshot") => b"{}\n",
                _ => b"\n",
            }
        }

    
        fn governance_artifact_projection_key(location: &GovernanceArtifactLocation) -> String {
            format!(
                "{}::{}::{}::{}",
                location
                    .project_id
                    .map_or_else(|| "global".to_string(), |id| id.to_string()),
                location.scope,
                location.artifact_kind,
                location.artifact_key
            )
        }

    
        fn next_governance_revision(
            state: &AppState,
            location: &GovernanceArtifactLocation,
            pending_revisions: &mut HashMap<String, u64>,
        ) -> u64 {
            let key = Self::governance_artifact_projection_key(location);
            if let Some(next) = pending_revisions.get_mut(&key) {
                *next = next.saturating_add(1);
                return *next;
            }
            let next = Self::governance_projection_for_location(state, location)
                .map_or(1, |existing| existing.revision.saturating_add(1));
            pending_revisions.insert(key, next);
            next
        }

    
        fn ensure_governance_layout(
            &self,
            project_id: Uuid,
            origin: &'static str,
        ) -> Result<Vec<PathBuf>> {
            let mut created = Vec::new();
            for location in self.governance_artifact_locations(project_id) {
                if location.is_dir {
                    if location.path.exists() {
                        if !location.path.is_dir() {
                            return Err(HivemindError::system(
                                "governance_path_conflict",
                                format!(
                                    "Expected governance directory at '{}' but found a file",
                                    location.path.display()
                                ),
                                origin,
                            ));
                        }
                    } else {
                        fs::create_dir_all(&location.path).map_err(|e| {
                            HivemindError::system(
                                "governance_storage_create_failed",
                                e.to_string(),
                                origin,
                            )
                        })?;
                        created.push(location.path.clone());
                    }
                    continue;
                }
    
                if let Some(parent) = location.path.parent() {
                    fs::create_dir_all(parent).map_err(|e| {
                        HivemindError::system("governance_storage_create_failed", e.to_string(), origin)
                    })?;
                }
    
                if location.path.exists() {
                    if location.path.is_dir() {
                        return Err(HivemindError::system(
                            "governance_path_conflict",
                            format!(
                                "Expected governance file at '{}' but found a directory",
                                location.path.display()
                            ),
                            origin,
                        ));
                    }
                } else {
                    fs::write(
                        &location.path,
                        Self::governance_default_file_contents(&location),
                    )
                    .map_err(|e| {
                        HivemindError::system("governance_storage_create_failed", e.to_string(), origin)
                    })?;
                    created.push(location.path.clone());
                }
            }
            Ok(created)
        }

    
        fn legacy_governance_mappings(
            &self,
            project: &Project,
        ) -> Vec<LegacyGovernanceArtifactMapping> {
            let mut mappings = Vec::new();
            let canonical = self.governance_artifact_locations(project.id);
            for repo in &project.repositories {
                let legacy_root = PathBuf::from(&repo.path).join(".hivemind");
                for destination in &canonical {
                    let source = if destination.scope == "project" {
                        legacy_root.join(&destination.artifact_key)
                    } else if destination.artifact_key == "notepad.md" {
                        legacy_root.join("global").join("notepad.md")
                    } else {
                        legacy_root.join("global").join(&destination.artifact_key)
                    };
                    mappings.push(LegacyGovernanceArtifactMapping {
                        source,
                        destination: destination.clone(),
                    });
                }
            }
            mappings
        }

    
        fn copy_dir_if_missing(
            source: &Path,
            destination: &Path,
            origin: &'static str,
        ) -> Result<bool> {
            if !source.exists() || !source.is_dir() {
                return Ok(false);
            }
    
            fs::create_dir_all(destination).map_err(|e| {
                HivemindError::system("governance_migration_failed", e.to_string(), origin)
            })?;
    
            let mut copied = false;
            let mut stack = vec![(source.to_path_buf(), destination.to_path_buf())];
            while let Some((src_dir, dst_dir)) = stack.pop() {
                for entry in fs::read_dir(&src_dir).map_err(|e| {
                    HivemindError::system("governance_migration_failed", e.to_string(), origin)
                })? {
                    let entry = entry.map_err(|e| {
                        HivemindError::system("governance_migration_failed", e.to_string(), origin)
                    })?;
                    let src_path = entry.path();
                    let dst_path = dst_dir.join(entry.file_name());
                    let file_type = entry.file_type().map_err(|e| {
                        HivemindError::system("governance_migration_failed", e.to_string(), origin)
                    })?;
                    if file_type.is_dir() {
                        fs::create_dir_all(&dst_path).map_err(|e| {
                            HivemindError::system("governance_migration_failed", e.to_string(), origin)
                        })?;
                        stack.push((src_path, dst_path));
                        continue;
                    }
    
                    if dst_path.exists() {
                        continue;
                    }
                    fs::copy(&src_path, &dst_path).map_err(|e| {
                        HivemindError::system("governance_migration_failed", e.to_string(), origin)
                    })?;
                    copied = true;
                }
            }
    
            Ok(copied)
        }

    
        fn copy_file_if_missing(
            source: &Path,
            destination: &Path,
            default_contents: Option<&[u8]>,
            origin: &'static str,
        ) -> Result<bool> {
            if !source.exists() || !source.is_file() {
                return Ok(false);
            }
            if destination.exists() {
                let source_bytes = fs::read(source).map_err(|e| {
                    HivemindError::system("governance_migration_failed", e.to_string(), origin)
                })?;
                if source_bytes.is_empty() {
                    return Ok(false);
                }
    
                let destination_bytes = fs::read(destination).map_err(|e| {
                    HivemindError::system("governance_migration_failed", e.to_string(), origin)
                })?;
                if destination_bytes == source_bytes {
                    return Ok(false);
                }
    
                let can_overwrite_scaffold = default_contents
                    .is_some_and(|default_bytes| destination_bytes.as_slice() == default_bytes);
                if !destination_bytes.is_empty() && !can_overwrite_scaffold {
                    return Ok(false);
                }
    
                fs::write(destination, source_bytes).map_err(|e| {
                    HivemindError::system("governance_migration_failed", e.to_string(), origin)
                })?;
                return Ok(true);
            }
            if let Some(parent) = destination.parent() {
                fs::create_dir_all(parent).map_err(|e| {
                    HivemindError::system("governance_migration_failed", e.to_string(), origin)
                })?;
            }
            fs::copy(source, destination).map_err(|e| {
                HivemindError::system("governance_migration_failed", e.to_string(), origin)
            })?;
            Ok(true)
        }

    
        fn validate_governance_identifier(
            raw: &str,
            field: &str,
            origin: &'static str,
        ) -> Result<String> {
            let trimmed = raw.trim();
            if trimmed.is_empty() {
                return Err(HivemindError::user(
                    "invalid_governance_identifier",
                    format!("{field} cannot be empty"),
                    origin,
                )
                .with_hint(
                    "Use lowercase letters, numbers, '.', '_' or '-' when naming governance artifacts",
                ));
            }
            if !trimmed
                .chars()
                .all(|c| c.is_ascii_alphanumeric() || matches!(c, '.' | '_' | '-'))
            {
                return Err(HivemindError::user(
                    "invalid_governance_identifier",
                    format!(
                        "{field} '{trimmed}' contains unsupported characters; only [a-zA-Z0-9._-] are allowed"
                    ),
                    origin,
                )
                .with_hint("Replace unsupported characters with '-', '_' or '.'"));
            }
            Ok(trimmed.to_string())
        }

    
        fn normalized_string_list(values: &[String]) -> Vec<String> {
            let mut out = Vec::new();
            let mut seen = HashSet::new();
            for value in values {
                let item = value.trim();
                if item.is_empty() {
                    continue;
                }
                let item_owned = item.to_string();
                if seen.insert(item_owned.clone()) {
                    out.push(item_owned);
                }
            }
            out
        }

    
        fn ensure_global_governance_layout(&self, origin: &'static str) -> Result<()> {
            let global_root = self.governance_global_root();
            fs::create_dir_all(global_root.join("skills")).map_err(|e| {
                HivemindError::system("governance_storage_create_failed", e.to_string(), origin)
            })?;
            fs::create_dir_all(global_root.join("system_prompts")).map_err(|e| {
                HivemindError::system("governance_storage_create_failed", e.to_string(), origin)
            })?;
            fs::create_dir_all(global_root.join("templates")).map_err(|e| {
                HivemindError::system("governance_storage_create_failed", e.to_string(), origin)
            })?;
            let notepad = global_root.join("notepad.md");
            if !notepad.exists() {
                fs::write(&notepad, b"\n").map_err(|e| {
                    HivemindError::system("governance_storage_create_failed", e.to_string(), origin)
                })?;
            }
            Ok(())
        }

    
        fn default_constitution_artifact() -> ConstitutionArtifact {
            ConstitutionArtifact {
                version: CONSTITUTION_VERSION,
                schema_version: CONSTITUTION_SCHEMA_VERSION.to_string(),
                compatibility: ConstitutionCompatibility {
                    minimum_hivemind_version: env!("CARGO_PKG_VERSION").to_string(),
                    governance_schema_version: GOVERNANCE_SCHEMA_VERSION.to_string(),
                },
                partitions: Vec::new(),
                rules: Vec::new(),
            }
        }

    
        fn constitution_path(&self, project_id: Uuid) -> PathBuf {
            self.governance_project_root(project_id)
                .join("constitution.yaml")
        }

    
        fn governance_constitution_location(&self, project_id: Uuid) -> GovernanceArtifactLocation {
            GovernanceArtifactLocation {
                project_id: Some(project_id),
                scope: "project",
                artifact_kind: "constitution",
                artifact_key: "constitution.yaml".to_string(),
                is_dir: false,
                path: self.constitution_path(project_id),
            }
        }

    
        fn governance_graph_snapshot_location(&self, project_id: Uuid) -> GovernanceArtifactLocation {
            GovernanceArtifactLocation {
                project_id: Some(project_id),
                scope: "project",
                artifact_kind: "graph_snapshot",
                artifact_key: "graph_snapshot.json".to_string(),
                is_dir: false,
                path: self.graph_snapshot_path(project_id),
            }
        }

        #[allow(clippy::too_many_lines)]
        fn validate_constitution(artifact: &ConstitutionArtifact) -> Vec<ConstitutionValidationIssue> {
            let mut issues = Vec::new();
    
            if artifact.version != CONSTITUTION_VERSION {
                issues.push(ConstitutionValidationIssue {
                    code: "constitution_version_unsupported".to_string(),
                    field: "version".to_string(),
                    message: format!(
                        "Unsupported constitution version {}; expected {CONSTITUTION_VERSION}",
                        artifact.version
                    ),
                });
            }
            if artifact.schema_version.trim() != CONSTITUTION_SCHEMA_VERSION {
                issues.push(ConstitutionValidationIssue {
                    code: "constitution_schema_version_unsupported".to_string(),
                    field: "schema_version".to_string(),
                    message: format!(
                        "Unsupported schema_version '{}'; expected '{CONSTITUTION_SCHEMA_VERSION}'",
                        artifact.schema_version
                    ),
                });
            }
            if artifact
                .compatibility
                .minimum_hivemind_version
                .trim()
                .is_empty()
            {
                issues.push(ConstitutionValidationIssue {
                    code: "constitution_minimum_hivemind_version_missing".to_string(),
                    field: "compatibility.minimum_hivemind_version".to_string(),
                    message: "minimum_hivemind_version cannot be empty".to_string(),
                });
            }
            if artifact.compatibility.governance_schema_version.trim() != GOVERNANCE_SCHEMA_VERSION {
                issues.push(ConstitutionValidationIssue {
                    code: "constitution_governance_schema_mismatch".to_string(),
                    field: "compatibility.governance_schema_version".to_string(),
                    message: format!("governance_schema_version must be '{GOVERNANCE_SCHEMA_VERSION}'"),
                });
            }
    
            let mut partition_ids = HashSet::new();
            let mut partition_paths = HashSet::new();
            for partition in &artifact.partitions {
                let partition_id = partition.id.trim();
                if partition_id.is_empty() {
                    issues.push(ConstitutionValidationIssue {
                        code: "constitution_partition_id_missing".to_string(),
                        field: "partitions[].id".to_string(),
                        message: "Partition id cannot be empty".to_string(),
                    });
                } else if !partition_ids.insert(partition_id.to_string()) {
                    issues.push(ConstitutionValidationIssue {
                        code: "constitution_partition_id_duplicate".to_string(),
                        field: format!("partitions.{}", partition.id),
                        message: format!("Duplicate partition id '{}'", partition.id),
                    });
                }
    
                let partition_path = partition.path.trim();
                if partition_path.is_empty() {
                    issues.push(ConstitutionValidationIssue {
                        code: "constitution_partition_path_missing".to_string(),
                        field: format!("partitions.{}.path", partition.id),
                        message: "Partition path cannot be empty".to_string(),
                    });
                } else if !partition_paths.insert(partition_path.to_string()) {
                    issues.push(ConstitutionValidationIssue {
                        code: "constitution_partition_path_duplicate".to_string(),
                        field: format!("partitions.{}.path", partition.id),
                        message: format!("Duplicate partition path '{}'", partition.path),
                    });
                }
            }
    
            let mut rule_ids = HashSet::new();
            for rule in &artifact.rules {
                let rule_id = rule.id().trim();
                if rule_id.is_empty() {
                    issues.push(ConstitutionValidationIssue {
                        code: "constitution_rule_id_missing".to_string(),
                        field: "rules[].id".to_string(),
                        message: "Rule id cannot be empty".to_string(),
                    });
                    continue;
                }
                if !rule_ids.insert(rule_id.to_string()) {
                    issues.push(ConstitutionValidationIssue {
                        code: "constitution_rule_id_duplicate".to_string(),
                        field: format!("rules.{rule_id}"),
                        message: format!("Duplicate rule id '{rule_id}'"),
                    });
                }
    
                match rule {
                    ConstitutionRule::ForbiddenDependency { from, to, .. }
                    | ConstitutionRule::AllowedDependency { from, to, .. } => {
                        if from.trim() == to.trim() {
                            issues.push(ConstitutionValidationIssue {
                                code: "constitution_rule_self_dependency".to_string(),
                                field: format!("rules.{rule_id}"),
                                message: "Rule cannot reference the same partition for from/to"
                                    .to_string(),
                            });
                        }
                        for (field, partition_ref) in [("from", from), ("to", to)] {
                            if partition_ref.trim().is_empty() {
                                issues.push(ConstitutionValidationIssue {
                                    code: "constitution_rule_partition_missing".to_string(),
                                    field: format!("rules.{rule_id}.{field}"),
                                    message: format!("Rule field '{field}' cannot be empty"),
                                });
                            } else if !partition_ids.contains(partition_ref.trim()) {
                                issues.push(ConstitutionValidationIssue {
                                    code: "constitution_rule_partition_unknown".to_string(),
                                    field: format!("rules.{rule_id}.{field}"),
                                    message: format!(
                                        "Rule references unknown partition '{partition_ref}'"
                                    ),
                                });
                            }
                        }
                    }
                    ConstitutionRule::CoverageRequirement {
                        target, threshold, ..
                    } => {
                        if target.trim().is_empty() {
                            issues.push(ConstitutionValidationIssue {
                                code: "constitution_rule_target_missing".to_string(),
                                field: format!("rules.{rule_id}.target"),
                                message: "Coverage target partition cannot be empty".to_string(),
                            });
                        } else if !partition_ids.contains(target.trim()) {
                            issues.push(ConstitutionValidationIssue {
                                code: "constitution_rule_target_unknown".to_string(),
                                field: format!("rules.{rule_id}.target"),
                                message: format!(
                                    "Coverage rule references unknown partition '{target}'"
                                ),
                            });
                        }
                        if *threshold > 100 {
                            issues.push(ConstitutionValidationIssue {
                                code: "constitution_rule_threshold_invalid".to_string(),
                                field: format!("rules.{rule_id}.threshold"),
                                message: "Coverage threshold must be between 0 and 100".to_string(),
                            });
                        }
                    }
                }
            }
    
            issues
        }

    
        fn read_constitution_artifact(
            &self,
            project_id: Uuid,
            origin: &'static str,
        ) -> Result<(ConstitutionArtifact, PathBuf)> {
            let path = self.constitution_path(project_id);
            if !path.is_file() {
                return Err(HivemindError::user(
                    "constitution_not_found",
                    "Project constitution is missing",
                    origin,
                )
                .with_hint("Run 'hivemind constitution init <project> --confirm' to initialize it"));
            }
            let raw = fs::read_to_string(&path).map_err(|e| {
                HivemindError::system("governance_artifact_read_failed", e.to_string(), origin)
                    .with_context("path", path.to_string_lossy().to_string())
            })?;
            let artifact = Self::parse_constitution_yaml(&raw, origin)
                .map_err(|err| err.with_context("path", path.to_string_lossy().to_string()))?;
            Ok((artifact, path))
        }

    
        fn parse_constitution_yaml(raw: &str, origin: &'static str) -> Result<ConstitutionArtifact> {
            serde_yaml::from_str(raw).map_err(|e| {
                HivemindError::user(
                    "constitution_schema_invalid",
                    format!("Malformed constitution YAML: {e}"),
                    origin,
                )
                .with_hint(
                    "Fix the constitution YAML schema and rerun 'hivemind constitution validate'",
                )
            })
        }

    
        fn write_constitution_artifact(
            path: &Path,
            artifact: &ConstitutionArtifact,
            origin: &'static str,
        ) -> Result<String> {
            let mut yaml = serde_yaml::to_string(artifact).map_err(|e| {
                HivemindError::system("constitution_serialize_failed", e.to_string(), origin)
            })?;
            if !yaml.ends_with('\n') {
                yaml.push('\n');
            }
            fs::write(path, yaml.as_bytes()).map_err(|e| {
                HivemindError::system("governance_artifact_write_failed", e.to_string(), origin)
                    .with_context("path", path.to_string_lossy().to_string())
            })?;
            Ok(Self::constitution_digest(yaml.as_bytes()))
        }

    
        fn constitution_digest(bytes: &[u8]) -> String {
            let mut hasher = std::collections::hash_map::DefaultHasher::new();
            bytes.hash(&mut hasher);
            format!("{:016x}", hasher.finish())
        }

    
        fn resolve_actor(actor: Option<&str>) -> String {
            actor
                .and_then(|value| {
                    let trimmed = value.trim();
                    (!trimmed.is_empty()).then(|| trimmed.to_string())
                })
                .or_else(|| {
                    env::var("USER")
                        .ok()
                        .filter(|value| !value.trim().is_empty())
                        .map(|value| value.trim().to_string())
                })
                .or_else(|| {
                    env::var("USERNAME")
                        .ok()
                        .filter(|value| !value.trim().is_empty())
                        .map(|value| value.trim().to_string())
                })
                .unwrap_or_else(|| "unknown".to_string())
        }

    
        fn project_document_path(&self, project_id: Uuid, document_id: &str) -> PathBuf {
            self.governance_project_root(project_id)
                .join("documents")
                .join(format!("{document_id}.json"))
        }

    
        fn global_skill_path(&self, skill_id: &str) -> PathBuf {
            self.governance_global_root()
                .join("skills")
                .join(format!("{skill_id}.json"))
        }

    
        fn global_system_prompt_path(&self, prompt_id: &str) -> PathBuf {
            self.governance_global_root()
                .join("system_prompts")
                .join(format!("{prompt_id}.json"))
        }

    
        fn global_template_path(&self, template_id: &str) -> PathBuf {
            self.governance_global_root()
                .join("templates")
                .join(format!("{template_id}.json"))
        }

    
        fn governance_document_location(
            &self,
            project_id: Uuid,
            document_id: &str,
        ) -> GovernanceArtifactLocation {
            GovernanceArtifactLocation {
                project_id: Some(project_id),
                scope: "project",
                artifact_kind: "document",
                artifact_key: document_id.to_string(),
                is_dir: false,
                path: self.project_document_path(project_id, document_id),
            }
        }

    
        fn governance_global_location(
            artifact_kind: &'static str,
            artifact_key: &str,
            path: PathBuf,
        ) -> GovernanceArtifactLocation {
            GovernanceArtifactLocation {
                project_id: None,
                scope: "global",
                artifact_kind,
                artifact_key: artifact_key.to_string(),
                is_dir: false,
                path,
            }
        }

    
        fn governance_notepad_location(&self, project_id: Option<Uuid>) -> GovernanceArtifactLocation {
            project_id.map_or_else(
                || GovernanceArtifactLocation {
                    project_id: None,
                    scope: "global",
                    artifact_kind: "notepad",
                    artifact_key: "notepad.md".to_string(),
                    is_dir: false,
                    path: self.governance_global_root().join("notepad.md"),
                },
                |project_id| GovernanceArtifactLocation {
                    project_id: Some(project_id),
                    scope: "project",
                    artifact_kind: "notepad",
                    artifact_key: "notepad.md".to_string(),
                    is_dir: false,
                    path: self.governance_project_root(project_id).join("notepad.md"),
                },
            )
        }

    
        fn governance_snapshot_root(&self, project_id: Uuid) -> PathBuf {
            self.governance_project_root(project_id)
                .join("recovery")
                .join("snapshots")
        }

    
        fn governance_snapshot_path(&self, project_id: Uuid, snapshot_id: &str) -> PathBuf {
            self.governance_snapshot_root(project_id)
                .join(format!("{snapshot_id}.json"))
        }

    
        fn governance_projection_key_from_parts(
            project_id: Option<Uuid>,
            scope: &str,
            artifact_kind: &str,
            artifact_key: &str,
        ) -> String {
            let project_key = project_id.map_or_else(|| "global".to_string(), |id| id.to_string());
            format!("{project_key}::{scope}::{artifact_kind}::{artifact_key}")
        }

    
        fn governance_location_for_path(
            &self,
            project_id: Uuid,
            path: &Path,
        ) -> Option<GovernanceArtifactLocation> {
            let project_root = self.governance_project_root(project_id);
            let global_root = self.governance_global_root();
            let documents_root = project_root.join("documents");
            let skills_root = global_root.join("skills");
            let prompts_root = global_root.join("system_prompts");
            let templates_root = global_root.join("templates");
    
            if path == self.constitution_path(project_id) {
                return Some(self.governance_constitution_location(project_id));
            }
            if path == self.graph_snapshot_path(project_id) {
                return Some(self.governance_graph_snapshot_location(project_id));
            }
            if path == self.governance_notepad_location(Some(project_id)).path {
                return Some(self.governance_notepad_location(Some(project_id)));
            }
            if path == self.governance_notepad_location(None).path {
                return Some(self.governance_notepad_location(None));
            }
    
            if path.starts_with(&documents_root) && path.extension().is_some_and(|ext| ext == "json") {
                let key = path.file_stem()?.to_str()?.to_string();
                return Some(self.governance_document_location(project_id, &key));
            }
    
            if path.starts_with(&skills_root) && path.extension().is_some_and(|ext| ext == "json") {
                let key = path.file_stem()?.to_str()?.to_string();
                return Some(Self::governance_global_location(
                    "skill",
                    &key,
                    path.to_path_buf(),
                ));
            }
    
            if path.starts_with(&prompts_root) && path.extension().is_some_and(|ext| ext == "json") {
                let key = path.file_stem()?.to_str()?.to_string();
                return Some(Self::governance_global_location(
                    "system_prompt",
                    &key,
                    path.to_path_buf(),
                ));
            }
    
            if path.starts_with(&templates_root) && path.extension().is_some_and(|ext| ext == "json") {
                let key = path.file_stem()?.to_str()?.to_string();
                return Some(Self::governance_global_location(
                    "template",
                    &key,
                    path.to_path_buf(),
                ));
            }
    
            None
        }

    
        fn governance_managed_file_locations(
            &self,
            project_id: Uuid,
            origin: &'static str,
        ) -> Result<Vec<GovernanceArtifactLocation>> {
            let mut out = Vec::new();
            let project_root = self.governance_project_root(project_id);
            let global_root = self.governance_global_root();
    
            let constitution = self.governance_constitution_location(project_id);
            if constitution.path.is_file() {
                out.push(constitution);
            }
            let graph_snapshot = self.governance_graph_snapshot_location(project_id);
            if graph_snapshot.path.is_file() {
                out.push(graph_snapshot);
            }
            let project_notepad = self.governance_notepad_location(Some(project_id));
            if project_notepad.path.is_file() {
                out.push(project_notepad);
            }
            let global_notepad = self.governance_notepad_location(None);
            if global_notepad.path.is_file() {
                out.push(global_notepad);
            }
    
            for path in Self::governance_json_paths(&project_root.join("documents"), origin)? {
                if let Some(location) = self.governance_location_for_path(project_id, &path) {
                    out.push(location);
                }
            }
            for path in Self::governance_json_paths(&global_root.join("skills"), origin)? {
                if let Some(location) = self.governance_location_for_path(project_id, &path) {
                    out.push(location);
                }
            }
            for path in Self::governance_json_paths(&global_root.join("system_prompts"), origin)? {
                if let Some(location) = self.governance_location_for_path(project_id, &path) {
                    out.push(location);
                }
            }
            for path in Self::governance_json_paths(&global_root.join("templates"), origin)? {
                if let Some(location) = self.governance_location_for_path(project_id, &path) {
                    out.push(location);
                }
            }
    
            out.sort_by(|a, b| {
                a.scope
                    .cmp(b.scope)
                    .then(a.artifact_kind.cmp(b.artifact_kind))
                    .then(a.artifact_key.cmp(&b.artifact_key))
                    .then(a.path.cmp(&b.path))
            });
            Ok(out)
        }

    
        fn load_snapshot_manifest(
            &self,
            project_id: Uuid,
            snapshot_id: &str,
            origin: &'static str,
        ) -> Result<GovernanceRecoverySnapshotManifest> {
            let path = self.governance_snapshot_path(project_id, snapshot_id);
            if !path.is_file() {
                return Err(HivemindError::user(
                    "governance_snapshot_not_found",
                    format!("Governance snapshot '{snapshot_id}' not found"),
                    origin,
                )
                .with_hint("Use 'hivemind project governance snapshot list <project>' to inspect available snapshots"));
            }
            let raw = fs::read_to_string(&path).map_err(|e| {
                HivemindError::system("governance_snapshot_read_failed", e.to_string(), origin)
                    .with_context("path", path.to_string_lossy().to_string())
            })?;
            serde_json::from_str::<GovernanceRecoverySnapshotManifest>(&raw).map_err(|e| {
                HivemindError::user(
                    "governance_snapshot_schema_invalid",
                    format!("Malformed governance snapshot '{snapshot_id}': {e}"),
                    origin,
                )
                .with_context("path", path.to_string_lossy().to_string())
                .with_hint("Delete the invalid snapshot and create a new one")
            })
        }

    
        fn list_snapshot_manifests(
            &self,
            project_id: Uuid,
            origin: &'static str,
        ) -> Result<Vec<(PathBuf, GovernanceRecoverySnapshotManifest)>> {
            let root = self.governance_snapshot_root(project_id);
            if !root.is_dir() {
                return Ok(Vec::new());
            }
            let mut items = Vec::new();
            for entry in fs::read_dir(&root).map_err(|e| {
                HivemindError::system("governance_snapshot_list_failed", e.to_string(), origin)
                    .with_context("path", root.to_string_lossy().to_string())
            })? {
                let entry = entry.map_err(|e| {
                    HivemindError::system("governance_snapshot_list_failed", e.to_string(), origin)
                })?;
                let path = entry.path();
                if !path.is_file() || path.extension().is_none_or(|ext| ext != "json") {
                    continue;
                }
                let raw = fs::read_to_string(&path).map_err(|e| {
                    HivemindError::system("governance_snapshot_read_failed", e.to_string(), origin)
                        .with_context("path", path.to_string_lossy().to_string())
                })?;
                let manifest = serde_json::from_str::<GovernanceRecoverySnapshotManifest>(&raw)
                    .map_err(|e| {
                        HivemindError::user(
                            "governance_snapshot_schema_invalid",
                            format!("Malformed governance snapshot at '{}': {e}", path.display()),
                            origin,
                        )
                        .with_context("path", path.to_string_lossy().to_string())
                    })?;
                if manifest.project_id == project_id {
                    items.push((path, manifest));
                }
            }
            items.sort_by(|a, b| b.1.created_at.cmp(&a.1.created_at));
            Ok(items)
        }

    
        fn append_governance_upsert_for_location(
            &self,
            state: &AppState,
            pending_revisions: &mut HashMap<String, u64>,
            location: &GovernanceArtifactLocation,
            corr: CorrelationIds,
            origin: &'static str,
        ) -> Result<u64> {
            let revision = Self::next_governance_revision(state, location, pending_revisions);
            self.append_event(
                Event::new(
                    EventPayload::GovernanceArtifactUpserted {
                        project_id: location.project_id,
                        scope: location.scope.to_string(),
                        artifact_kind: location.artifact_kind.to_string(),
                        artifact_key: location.artifact_key.clone(),
                        path: location.path.to_string_lossy().to_string(),
                        revision,
                        schema_version: GOVERNANCE_SCHEMA_VERSION.to_string(),
                        projection_version: GOVERNANCE_PROJECTION_VERSION,
                    },
                    corr,
                ),
                origin,
            )?;
            Ok(revision)
        }

    
        fn append_governance_delete_for_location(
            &self,
            location: &GovernanceArtifactLocation,
            corr: CorrelationIds,
            origin: &'static str,
        ) -> Result<()> {
            self.append_event(
                Event::new(
                    EventPayload::GovernanceArtifactDeleted {
                        project_id: location.project_id,
                        scope: location.scope.to_string(),
                        artifact_kind: location.artifact_kind.to_string(),
                        artifact_key: location.artifact_key.clone(),
                        path: location.path.to_string_lossy().to_string(),
                        schema_version: GOVERNANCE_SCHEMA_VERSION.to_string(),
                        projection_version: GOVERNANCE_PROJECTION_VERSION,
                    },
                    corr,
                ),
                origin,
            )
        }

    
        fn read_project_document_artifact(
            &self,
            project_id: Uuid,
            document_id: &str,
            origin: &'static str,
        ) -> Result<ProjectDocumentArtifact> {
            let path = self.project_document_path(project_id, document_id);
            if !path.is_file() {
                return Err(HivemindError::user(
                    "document_not_found",
                    format!("Project document '{document_id}' not found"),
                    origin,
                )
                .with_hint("Use 'hivemind project governance document list <project>' to inspect available documents"));
            }
            let artifact = Self::read_governance_json::<ProjectDocumentArtifact>(
                &path,
                "project_document",
                document_id,
                origin,
            )?;
            if artifact.document_id != document_id {
                return Err(HivemindError::user(
                    "governance_artifact_schema_invalid",
                    format!(
                        "Document file key mismatch: expected '{document_id}', found '{}'",
                        artifact.document_id
                    ),
                    origin,
                )
                .with_context("path", path.to_string_lossy().to_string()));
            }
            if artifact.revisions.is_empty() {
                return Err(HivemindError::user(
                    "governance_artifact_schema_invalid",
                    format!("Document '{document_id}' has no revision history"),
                    origin,
                )
                .with_hint("Repair the document JSON to include at least one revision"));
            }
            Ok(artifact)
        }

    
        fn governance_document_attachment_states(
            state: &AppState,
            project_id: Uuid,
            task_id: Uuid,
        ) -> (Vec<String>, Vec<String>) {
            let mut included = Vec::new();
            let mut excluded = Vec::new();
            for item in state.governance_attachments.values().filter(|item| {
                item.project_id == project_id
                    && item.task_id == task_id
                    && item.artifact_kind == "document"
            }) {
                if item.attached {
                    included.push(item.artifact_key.clone());
                } else {
                    excluded.push(item.artifact_key.clone());
                }
            }
            included.sort();
            included.dedup();
            excluded.sort();
            excluded.dedup();
            (included, excluded)
        }

    
        fn governance_artifact_revision(
            state: &AppState,
            project_id: Option<Uuid>,
            scope: &str,
            artifact_kind: &str,
            artifact_key: &str,
        ) -> Option<u64> {
            state
                .governance_artifacts
                .values()
                .find(|item| {
                    item.project_id == project_id
                        && item.scope == scope
                        && item.artifact_kind == artifact_kind
                        && item.artifact_key == artifact_key
                })
                .map(|item| item.revision)
        }

    
        fn latest_template_instantiation_snapshot(
            &self,
            project_id: Uuid,
        ) -> Result<Option<TemplateInstantiationSnapshot>> {
            let events = self.read_events(&EventFilter::for_project(project_id))?;
            let mut snapshot: Option<TemplateInstantiationSnapshot> = None;
            for event in events {
                let event_id = event.id().as_uuid().to_string();
                if let EventPayload::TemplateInstantiated {
                    project_id: event_project_id,
                    template_id,
                    system_prompt_id,
                    skill_ids,
                    document_ids,
                    schema_version,
                    projection_version,
                } = event.payload
                {
                    if event_project_id != project_id {
                        continue;
                    }
                    snapshot = Some(TemplateInstantiationSnapshot {
                        event_id,
                        template_id,
                        system_prompt_id,
                        skill_ids,
                        document_ids,
                        schema_version,
                        projection_version,
                    });
                }
            }
            Ok(snapshot)
        }

    
        fn attempt_manifest_hash_for_attempt(&self, attempt_id: Uuid) -> Result<Option<String>> {
            let filter = EventFilter {
                attempt_id: Some(attempt_id),
                ..EventFilter::default()
            };
            let events = self.read_events(&filter)?;
            let mut manifest_hash = None;
            for event in events {
                if let EventPayload::AttemptContextAssembled {
                    manifest_hash: hash,
                    ..
                } = event.payload
                {
                    manifest_hash = Some(hash);
                }
            }
            Ok(manifest_hash)
        }

    
        fn read_global_skill_artifact(
            &self,
            skill_id: &str,
            origin: &'static str,
        ) -> Result<GlobalSkillArtifact> {
            let path = self.global_skill_path(skill_id);
            if !path.is_file() {
                return Err(HivemindError::user(
                    "skill_not_found",
                    format!("Global skill '{skill_id}' not found"),
                    origin,
                )
                .with_hint("Use 'hivemind global skill list' to inspect available skills"));
            }
            let artifact = Self::read_governance_json::<GlobalSkillArtifact>(
                &path,
                "global_skill",
                skill_id,
                origin,
            )?;
            if artifact.skill_id != skill_id {
                return Err(HivemindError::user(
                    "governance_artifact_schema_invalid",
                    format!(
                        "Skill file key mismatch: expected '{skill_id}', found '{}'",
                        artifact.skill_id
                    ),
                    origin,
                )
                .with_context("path", path.to_string_lossy().to_string()));
            }
            Ok(artifact)
        }

    
        fn read_global_system_prompt_artifact(
            &self,
            prompt_id: &str,
            origin: &'static str,
        ) -> Result<GlobalSystemPromptArtifact> {
            let path = self.global_system_prompt_path(prompt_id);
            if !path.is_file() {
                return Err(HivemindError::user(
                    "system_prompt_not_found",
                    format!("Global system prompt '{prompt_id}' not found"),
                    origin,
                )
                .with_hint(
                    "Use 'hivemind global system-prompt list' to inspect available system prompts",
                ));
            }
            let artifact = Self::read_governance_json::<GlobalSystemPromptArtifact>(
                &path,
                "global_system_prompt",
                prompt_id,
                origin,
            )?;
            if artifact.prompt_id != prompt_id {
                return Err(HivemindError::user(
                    "governance_artifact_schema_invalid",
                    format!(
                        "System prompt file key mismatch: expected '{prompt_id}', found '{}'",
                        artifact.prompt_id
                    ),
                    origin,
                )
                .with_context("path", path.to_string_lossy().to_string()));
            }
            Ok(artifact)
        }

    
        fn read_global_template_artifact(
            &self,
            template_id: &str,
            origin: &'static str,
        ) -> Result<GlobalTemplateArtifact> {
            let path = self.global_template_path(template_id);
            if !path.is_file() {
                return Err(HivemindError::user(
                    "template_not_found",
                    format!("Global template '{template_id}' not found"),
                    origin,
                )
                .with_hint("Use 'hivemind global template list' to inspect available templates"));
            }
            let artifact = Self::read_governance_json::<GlobalTemplateArtifact>(
                &path,
                "global_template",
                template_id,
                origin,
            )?;
            if artifact.template_id != template_id {
                return Err(HivemindError::user(
                    "governance_artifact_schema_invalid",
                    format!(
                        "Template file key mismatch: expected '{template_id}', found '{}'",
                        artifact.template_id
                    ),
                    origin,
                )
                .with_context("path", path.to_string_lossy().to_string()));
            }
            Ok(artifact)
        }

    
        fn governance_json_paths(dir: &Path, origin: &'static str) -> Result<Vec<PathBuf>> {
            let mut paths = Vec::new();
            if !dir.is_dir() {
                return Ok(paths);
            }
            for entry in fs::read_dir(dir).map_err(|e| {
                HivemindError::system("governance_artifact_read_failed", e.to_string(), origin)
                    .with_context("path", dir.to_string_lossy().to_string())
            })? {
                let entry = entry.map_err(|e| {
                    HivemindError::system("governance_artifact_read_failed", e.to_string(), origin)
                        .with_context("path", dir.to_string_lossy().to_string())
                })?;
                let path = entry.path();
                if path
                    .extension()
                    .and_then(|ext| ext.to_str())
                    .is_some_and(|ext| ext.eq_ignore_ascii_case("json"))
                {
                    paths.push(path);
                }
            }
            paths.sort();
            Ok(paths)
        }

    
        fn project_document_summary_from_artifact(
            project_id: Uuid,
            artifact: &ProjectDocumentArtifact,
            path: &Path,
        ) -> ProjectGovernanceDocumentSummary {
            let revision = artifact.revisions.last().map_or(0, |rev| rev.revision);
            ProjectGovernanceDocumentSummary {
                project_id,
                document_id: artifact.document_id.clone(),
                title: artifact.title.clone(),
                owner: artifact.owner.clone(),
                tags: artifact.tags.clone(),
                updated_at: artifact.updated_at,
                revision,
                path: path.to_string_lossy().to_string(),
            }
        }

}
