//! Auto-generated registry split module: registry.
//!
//! Generated by scripts/registry_split_migrator.py.

use crate::core::registry::Registry;

// RegistryConfig (89-93)
#[derive(Debug, Clone)]
pub struct RegistryConfig {
    /// Base directory for hivemind data.
    pub data_dir: PathBuf,
}

// Registry (129-133)
/// The project registry manages projects via event sourcing.
pub struct Registry {
    store: Arc<dyn EventStore>,
    config: RegistryConfig,
}

// RegistryConfig (95-127)
impl RegistryConfig {
    /// Creates a new config with default data directory.
    #[must_use]
    pub fn default_dir() -> Self {
        if let Ok(data_dir) = env::var("HIVEMIND_DATA_DIR") {
            return Self {
                data_dir: PathBuf::from(data_dir),
            };
        }

        let data_dir =
            dirs::home_dir().map_or_else(|| PathBuf::from(".hivemind"), |h| h.join(".hivemind"));
        Self { data_dir }
    }

    /// Creates a config with custom data directory.
    #[must_use]
    pub fn with_dir(data_dir: PathBuf) -> Self {
        Self { data_dir }
    }

    /// Returns the path to the legacy events JSONL mirror file.
    #[must_use]
    pub fn events_path(&self) -> PathBuf {
        self.data_dir.join("events.jsonl")
    }

    /// Returns the path to the canonical `SQLite` database file.
    #[must_use]
    pub fn db_path(&self) -> PathBuf {
        self.data_dir.join("db.sqlite")
    }
}

impl Registry {
    
        fn prepare_runtime_environment(
            runtime: &mut ProjectRuntimeConfig,
            origin: &'static str,
        ) -> Result<RuntimeEnvironmentProvenance> {
            let built = build_protected_runtime_environment(&runtime.env)
                .map_err(|error| Self::runtime_env_build_error(error, origin))?;
            runtime.env = built.env;
            Ok(built.provenance)
        }

    
        fn has_model_flag(args: &[String], short_alias: bool) -> bool {
            args.iter().any(|arg| {
                arg == "--model" || arg.starts_with("--model=") || (short_alias && arg == "-m")
            })
        }

    
        fn blobs_dir(&self) -> PathBuf {
            self.config.data_dir.join("blobs")
        }

    
        fn blob_path_for_digest(&self, digest: &str) -> PathBuf {
            let prefix = digest.get(..2).unwrap_or("00");
            self.blobs_dir()
                .join("sha256")
                .join(prefix)
                .join(format!("{digest}.blob"))
        }

    
        fn write_baseline_artifact(&self, baseline: &Baseline) -> Result<()> {
            let files_dir = self.baseline_files_dir(baseline.id);
            fs::create_dir_all(&files_dir).map_err(|e| {
                HivemindError::system(
                    "artifact_write_failed",
                    e.to_string(),
                    "registry:write_baseline_artifact",
                )
            })?;
    
            let json = serde_json::to_vec_pretty(baseline).map_err(|e| {
                HivemindError::system(
                    "artifact_serialize_failed",
                    e.to_string(),
                    "registry:write_baseline_artifact",
                )
            })?;
            fs::write(self.baseline_json_path(baseline.id), json).map_err(|e| {
                HivemindError::system(
                    "artifact_write_failed",
                    e.to_string(),
                    "registry:write_baseline_artifact",
                )
            })?;
    
            for snapshot in baseline.files.values() {
                if snapshot.is_dir {
                    continue;
                }
    
                let src = baseline.root.join(&snapshot.path);
                let dst = files_dir.join(&snapshot.path);
                if let Some(parent) = dst.parent() {
                    fs::create_dir_all(parent).map_err(|e| {
                        HivemindError::system(
                            "artifact_write_failed",
                            e.to_string(),
                            "registry:write_baseline_artifact",
                        )
                    })?;
                }
    
                let Ok(contents) = fs::read(src) else {
                    continue;
                };
                let _ = fs::write(dst, contents);
            }
            Ok(())
        }

    
        fn read_baseline_artifact(&self, baseline_id: Uuid) -> Result<Baseline> {
            let bytes = fs::read(self.baseline_json_path(baseline_id)).map_err(|e| {
                HivemindError::system(
                    "artifact_read_failed",
                    e.to_string(),
                    "registry:read_baseline_artifact",
                )
            })?;
            serde_json::from_slice(&bytes).map_err(|e| {
                HivemindError::system(
                    "artifact_deserialize_failed",
                    e.to_string(),
                    "registry:read_baseline_artifact",
                )
            })
        }

    
        fn write_diff_artifact(&self, artifact: &DiffArtifact) -> Result<()> {
            fs::create_dir_all(self.diffs_dir()).map_err(|e| {
                HivemindError::system(
                    "artifact_write_failed",
                    e.to_string(),
                    "registry:write_diff_artifact",
                )
            })?;
            let json = serde_json::to_vec_pretty(artifact).map_err(|e| {
                HivemindError::system(
                    "artifact_serialize_failed",
                    e.to_string(),
                    "registry:write_diff_artifact",
                )
            })?;
            fs::write(self.diff_json_path(artifact.diff.id), json).map_err(|e| {
                HivemindError::system(
                    "artifact_write_failed",
                    e.to_string(),
                    "registry:write_diff_artifact",
                )
            })?;
            Ok(())
        }

    
        fn read_diff_artifact(&self, diff_id: Uuid) -> Result<DiffArtifact> {
            let bytes = fs::read(self.diff_json_path(diff_id)).map_err(|e| {
                HivemindError::system(
                    "artifact_read_failed",
                    e.to_string(),
                    "registry:read_diff_artifact",
                )
            })?;
            serde_json::from_slice(&bytes).map_err(|e| {
                HivemindError::system(
                    "artifact_deserialize_failed",
                    e.to_string(),
                    "registry:read_diff_artifact",
                )
            })
        }

    
        fn unified_diff_for_change(
            &self,
            baseline_id: Uuid,
            worktree_root: &std::path::Path,
            change: &FileChange,
        ) -> std::io::Result<String> {
            let baseline_files = self.baseline_files_dir(baseline_id);
            let old = baseline_files.join(&change.path);
            let new = worktree_root.join(&change.path);
    
            match change.change_type {
                ChangeType::Created => unified_diff(None, Some(&new)),
                ChangeType::Deleted => unified_diff(Some(&old), None),
                ChangeType::Modified => unified_diff(Some(&old), Some(&new)),
            }
        }

        /// Opens or creates a registry at the default location.
        ///
        /// # Errors
        /// Returns an error if the event store cannot be opened.
        pub fn open() -> Result<Self> {
            Self::open_with_config(RegistryConfig::default_dir())
        }

        /// Opens or creates a registry with custom config.
        ///
        /// # Errors
        /// Returns an error if the event store cannot be opened.
        pub fn open_with_config(config: RegistryConfig) -> Result<Self> {
            let store = SqliteEventStore::open(&config.data_dir).map_err(|e| {
                HivemindError::system("store_open_failed", e.to_string(), "registry:open")
            })?;
    
            Ok(Self {
                store: Arc::new(store),
                config,
            })
        }

        /// Creates a registry with a custom event store (for testing).
        #[must_use]
        pub fn with_store(store: Arc<dyn EventStore>, config: RegistryConfig) -> Self {
            Self { store, config }
        }

        /// Gets the current state by replaying all events.
        ///
        /// # Errors
        /// Returns an error if events cannot be read.
        pub fn state(&self) -> Result<AppState> {
            let events = self.store.read_all().map_err(|e| {
                HivemindError::system("state_read_failed", e.to_string(), "registry:state")
            })?;
            Ok(AppState::replay(&events))
        }

        /// Lists events in the store.
        ///
        /// # Errors
        /// Returns an error if events cannot be read.
        pub fn list_events(&self, project_id: Option<Uuid>, limit: usize) -> Result<Vec<Event>> {
            let mut filter = EventFilter::all();
            filter.project_id = project_id;
            filter.limit = Some(limit);
    
            self.store.read(&filter).map_err(|e| {
                HivemindError::system("event_read_failed", e.to_string(), "registry:list_events")
            })
        }

}
