//! Auto-generated registry split module: runtime.
//!
//! Generated by scripts/registry_split_migrator.py.

use crate::core::registry::Registry;

impl Registry {
    
        fn runtime_env_build_error(error: RuntimeEnvBuildError, origin: &'static str) -> HivemindError {
            HivemindError::runtime(error.code, error.message, origin).recoverable(false)
        }

    
        fn runtime_start_flags(runtime: &ProjectRuntimeConfig) -> Vec<String> {
            match runtime.adapter_name.as_str() {
                "codex" => {
                    let mut flags = if runtime.args.is_empty() {
                        CodexConfig::default().base.args
                    } else {
                        runtime.args.clone()
                    };
    
                    if let Some(model) = runtime.model.as_ref() {
                        if !Self::has_model_flag(&flags, false) {
                            flags.extend(["--model".to_string(), model.clone()]);
                        }
                    }
    
                    flags
                }
                "claude-code" => {
                    let mut flags = if runtime.args.is_empty() {
                        ClaudeCodeConfig::default().base.args
                    } else {
                        runtime.args.clone()
                    };
    
                    if let Some(model) = runtime.model.as_ref() {
                        if !Self::has_model_flag(&flags, false) {
                            flags.extend(["--model".to_string(), model.clone()]);
                        }
                    }
    
                    flags
                }
                "opencode" | "kilo" => {
                    let mut flags = runtime.args.clone();
                    let is_opencode_binary = PathBuf::from(&runtime.binary_path)
                        .file_name()
                        .and_then(|s| s.to_str())
                        .is_some_and(|s| {
                            let lower = s.to_ascii_lowercase();
                            lower.contains("opencode") || lower.contains("kilo")
                        });
    
                    if is_opencode_binary {
                        let mut with_start = vec!["run".to_string()];
                        if let Some(model) = runtime.model.as_ref() {
                            if !Self::has_model_flag(&flags, true) {
                                with_start.extend(["--model".to_string(), model.clone()]);
                            }
                        }
                        with_start.append(&mut flags);
                        with_start
                    } else {
                        flags
                    }
                }
                "native" => {
                    let mut flags = vec![
                        format!("--max-turns={}", NativeRuntimeConfig::default().max_turns),
                        format!(
                            "--token-budget={}",
                            NativeRuntimeConfig::default().token_budget
                        ),
                    ];
                    flags.extend(runtime.args.clone());
                    flags
                }
                _ => runtime.args.clone(),
            }
        }

    
        fn runtime_descriptor_for_adapter(adapter: &str) -> Option<crate::adapters::RuntimeDescriptor> {
            runtime_descriptors()
                .into_iter()
                .find(|descriptor| descriptor.adapter_name == adapter)
        }

    
        fn runtime_capabilities_for_adapter(adapter: &str) -> Vec<String> {
            Self::runtime_descriptor_for_adapter(adapter)
                .map(|descriptor| {
                    descriptor
                        .capabilities
                        .iter()
                        .map(|capability| (*capability).to_string())
                        .collect::<Vec<_>>()
                })
                .unwrap_or_default()
        }

    
        fn classify_runtime_error(
            code: &str,
            message: &str,
            recoverable: bool,
            stdout: &str,
            stderr: &str,
        ) -> ClassifiedRuntimeError {
            let combined = format!("{code} {message} {stdout} {stderr}").to_ascii_lowercase();
            let rate_limited = combined.contains("rate limit")
                || combined.contains("rate_limit")
                || combined.contains("too many requests")
                || combined.contains(" 429")
                || combined.contains("status 429")
                || combined.contains("http 429");
    
            let category = if rate_limited {
                "rate_limit"
            } else if code.starts_with("native_stream_") {
                "transport_stream"
            } else if code.starts_with("native_transport_") {
                "transport"
            } else if code == "timeout" {
                "timeout"
            } else if code == "checkpoints_incomplete" {
                "checkpoint_incomplete"
            } else if matches!(
                code,
                "binary_not_found" | "health_check_failed" | "missing_args" | "worktree_not_found"
            ) {
                "configuration"
            } else if code.contains("initialize") || code.contains("prepare") {
                "runtime_setup"
            } else {
                "runtime_execution"
            };
    
            let effective_recoverable = recoverable || rate_limited || code == "checkpoints_incomplete";
            let retryable = effective_recoverable
                && !matches!(
                    code,
                    "binary_not_found"
                        | "health_check_failed"
                        | "missing_args"
                        | "worktree_not_found"
                        | "checkpoints_incomplete"
                );
    
            ClassifiedRuntimeError {
                code: code.to_string(),
                category: category.to_string(),
                message: message.to_string(),
                recoverable: effective_recoverable,
                retryable,
                rate_limited,
            }
        }

    
        fn detect_runtime_output_failure(stdout: &str, stderr: &str) -> Option<(String, String, bool)> {
            let combined = format!("{stdout}\n{stderr}").to_ascii_lowercase();
    
            if combined.contains("incorrect api key")
                || combined.contains("invalid api key")
                || combined.contains("authentication failed")
                || combined.contains("unauthorized")
                || combined.contains("forbidden")
            {
                return Some((
                    "runtime_auth_failed".to_string(),
                    "Runtime authentication failed; inspect runtime stderr for details".to_string(),
                    false,
                ));
            }
    
            if combined.contains("rate limit")
                || combined.contains("too many requests")
                || combined.contains("http 429")
                || combined.contains("status 429")
                || combined.contains(" 429")
            {
                return Some((
                    "runtime_rate_limited".to_string(),
                    "Runtime reported rate limiting; retry recommended".to_string(),
                    true,
                ));
            }
    
            None
        }

    
        fn emit_runtime_error_classified(
            &self,
            flow: &TaskFlow,
            task_id: Uuid,
            attempt_id: Uuid,
            adapter_name: &str,
            classified: &ClassifiedRuntimeError,
            origin: &'static str,
        ) -> Result<()> {
            let corr_attempt = CorrelationIds::for_graph_flow_task_attempt(
                flow.project_id,
                flow.graph_id,
                flow.id,
                task_id,
                attempt_id,
            );
    
            self.append_event(
                Event::new(
                    EventPayload::RuntimeErrorClassified {
                        attempt_id,
                        adapter_name: adapter_name.to_string(),
                        code: classified.code.clone(),
                        category: classified.category.clone(),
                        message: classified.message.clone(),
                        recoverable: classified.recoverable,
                        retryable: classified.retryable,
                        rate_limited: classified.rate_limited,
                    },
                    corr_attempt.clone(),
                ),
                origin,
            )?;
    
            let mut err = HivemindError::runtime(
                format!("runtime_{}", classified.code),
                classified.message.clone(),
                origin,
            )
            .recoverable(classified.recoverable)
            .with_context("adapter", adapter_name.to_string())
            .with_context("runtime_error_code", classified.code.clone())
            .with_context("runtime_error_category", classified.category.clone());
    
            if classified.rate_limited {
                err = err.with_hint(
                    "Rate limiting detected. Hivemind will schedule a retry and may switch to a backup runtime if configured.",
                );
            }
    
            self.record_error_event(&err, corr_attempt);
            Ok(())
        }

    
        fn select_runtime_backup(
            state: &AppState,
            flow: &TaskFlow,
            task_id: Uuid,
            primary: &ProjectRuntimeConfig,
        ) -> Option<ProjectRuntimeConfig> {
            if let Ok(candidate) = Self::effective_runtime_for_task(
                state,
                flow,
                task_id,
                RuntimeRole::Validator,
                "registry:tick_flow",
            ) {
                if candidate != *primary {
                    return Some(candidate);
                }
            }
    
            match primary.adapter_name.as_str() {
                "opencode" => {
                    let mut fallback = primary.clone();
                    fallback.adapter_name = "kilo".to_string();
                    Some(fallback)
                }
                "kilo" => {
                    let mut fallback = primary.clone();
                    fallback.adapter_name = "opencode".to_string();
                    Some(fallback)
                }
                _ => None,
            }
        }

        #[allow(clippy::too_many_arguments)]
        fn schedule_runtime_recovery(
            &self,
            state: &AppState,
            flow: &TaskFlow,
            task_id: Uuid,
            attempt_id: Uuid,
            from_runtime: &ProjectRuntimeConfig,
            classified: &ClassifiedRuntimeError,
            origin: &'static str,
        ) -> Result<()> {
            let backup = Self::select_runtime_backup(state, flow, task_id, from_runtime);
            let target_runtime = if classified.rate_limited {
                backup.unwrap_or_else(|| from_runtime.clone())
            } else {
                from_runtime.clone()
            };
    
            let strategy = if target_runtime.adapter_name == from_runtime.adapter_name {
                "same_runtime_retry"
            } else {
                "fallback_runtime"
            };
            let backoff_ms = if classified.rate_limited { 1_000 } else { 250 };
    
            let corr_attempt = CorrelationIds::for_graph_flow_task_attempt(
                flow.project_id,
                flow.graph_id,
                flow.id,
                task_id,
                attempt_id,
            );
            self.append_event(
                Event::new(
                    EventPayload::RuntimeRecoveryScheduled {
                        attempt_id,
                        from_adapter: from_runtime.adapter_name.clone(),
                        to_adapter: target_runtime.adapter_name.clone(),
                        strategy: strategy.to_string(),
                        reason: classified.code.clone(),
                        backoff_ms,
                    },
                    corr_attempt,
                ),
                origin,
            )?;
    
            if target_runtime.adapter_name != from_runtime.adapter_name {
                let corr_task = CorrelationIds::for_graph_flow_task(
                    flow.project_id,
                    flow.graph_id,
                    flow.id,
                    task_id,
                );
                self.append_event(
                    Event::new(
                        EventPayload::TaskRuntimeRoleConfigured {
                            task_id,
                            role: RuntimeRole::Worker,
                            adapter_name: target_runtime.adapter_name,
                            binary_path: target_runtime.binary_path,
                            model: target_runtime.model,
                            args: target_runtime.args,
                            env: target_runtime.env,
                            timeout_ms: target_runtime.timeout_ms,
                        },
                        corr_task,
                    ),
                    origin,
                )?;
            }
            Ok(())
        }

        #[allow(clippy::too_many_arguments)]
        fn handle_runtime_failure(
            &self,
            state: &AppState,
            flow: &TaskFlow,
            task_id: Uuid,
            attempt_id: Uuid,
            runtime: &ProjectRuntimeConfig,
            next_attempt_number: u32,
            max_attempts: u32,
            failure_code: &str,
            failure_message: &str,
            recoverable: bool,
            stdout: &str,
            stderr: &str,
            origin: &'static str,
        ) -> Result<()> {
            let corr_attempt = CorrelationIds::for_graph_flow_task_attempt(
                flow.project_id,
                flow.graph_id,
                flow.id,
                task_id,
                attempt_id,
            );
    
            let reason = format!("{failure_code}: {failure_message}");
            self.append_event(
                Event::new(
                    EventPayload::RuntimeTerminated { attempt_id, reason },
                    corr_attempt.clone(),
                ),
                origin,
            )?;
    
            let classified = Self::classify_runtime_error(
                failure_code,
                failure_message,
                recoverable,
                stdout,
                stderr,
            );
            self.emit_runtime_error_classified(
                flow,
                task_id,
                attempt_id,
                &runtime.adapter_name,
                &classified,
                origin,
            )?;
    
            if failure_code == "checkpoints_incomplete" {
                return Ok(());
            }
    
            self.fail_running_attempt(flow, task_id, attempt_id, failure_code, origin)?;
    
            let should_retry = classified.retryable
                && next_attempt_number < max_attempts
                && (classified.rate_limited
                    || matches!(
                        classified.code.as_str(),
                        "timeout" | "wait_failed" | "stdin_write_failed"
                    )
                    || classified.code.starts_with("native_transport_")
                    || classified.code.starts_with("native_stream_"));
    
            if should_retry {
                self.schedule_runtime_recovery(
                    state,
                    flow,
                    task_id,
                    attempt_id,
                    runtime,
                    &classified,
                    origin,
                )?;
                if let Err(err) = self.retry_task(&task_id.to_string(), false, RetryMode::Continue) {
                    self.record_error_event(&err, corr_attempt);
                }
            }
    
            Ok(())
        }

    
        fn projected_runtime_event_payload(
            attempt_id: Uuid,
            observation: ProjectedRuntimeObservation,
        ) -> EventPayload {
            match observation {
                ProjectedRuntimeObservation::CommandObserved { stream, command } => {
                    EventPayload::RuntimeCommandObserved {
                        attempt_id,
                        stream,
                        command,
                    }
                }
                ProjectedRuntimeObservation::ToolCallObserved {
                    stream,
                    tool_name,
                    details,
                } => EventPayload::RuntimeToolCallObserved {
                    attempt_id,
                    stream,
                    tool_name,
                    details,
                },
                ProjectedRuntimeObservation::TodoSnapshotUpdated { stream, items } => {
                    EventPayload::RuntimeTodoSnapshotUpdated {
                        attempt_id,
                        stream,
                        items,
                    }
                }
                ProjectedRuntimeObservation::NarrativeOutputObserved { stream, content } => {
                    EventPayload::RuntimeNarrativeOutputObserved {
                        attempt_id,
                        stream,
                        content,
                    }
                }
            }
        }

    
        fn append_projected_runtime_observations(
            &self,
            attempt_id: Uuid,
            correlation: &CorrelationIds,
            observations: Vec<ProjectedRuntimeObservation>,
            origin: &'static str,
        ) -> Result<()> {
            for observation in observations {
                self.append_event(
                    Event::new(
                        Self::projected_runtime_event_payload(attempt_id, observation),
                        correlation.clone(),
                    ),
                    origin,
                )?;
            }
            Ok(())
        }

    
        fn native_capture_mode_for_event(
            mode: NativePayloadCaptureMode,
        ) -> NativeEventPayloadCaptureMode {
            match mode {
                NativePayloadCaptureMode::MetadataOnly => NativeEventPayloadCaptureMode::MetadataOnly,
                NativePayloadCaptureMode::FullPayload => NativeEventPayloadCaptureMode::FullPayload,
            }
        }

    
        fn native_event_correlation(
            flow: &TaskFlow,
            task_id: Uuid,
            attempt_id: Uuid,
        ) -> NativeEventCorrelation {
            NativeEventCorrelation {
                project_id: flow.project_id,
                graph_id: flow.graph_id,
                flow_id: flow.id,
                task_id,
                attempt_id,
            }
        }

    
        fn native_blob_sha256(payload: &[u8]) -> String {
            let mut hasher = Sha256::new();
            hasher.update(payload);
            let digest = hasher.finalize();
            let mut hex = String::with_capacity(digest.len() * 2);
            for byte in digest {
                let _ = write!(&mut hex, "{byte:02x}");
            }
            hex
        }

    
        fn persist_native_blob(
            &self,
            media_type: &str,
            payload: &str,
            mode: NativePayloadCaptureMode,
            origin: &'static str,
        ) -> Result<NativeBlobRef> {
            let payload_bytes = payload.as_bytes();
            let digest = Self::native_blob_sha256(payload_bytes);
            let blob_path = self.blob_path_for_digest(&digest);
            if let Some(parent) = blob_path.parent() {
                fs::create_dir_all(parent).map_err(|e| {
                    HivemindError::system("blob_write_failed", e.to_string(), origin)
                        .with_context("path", parent.display().to_string())
                })?;
            }
            if !blob_path.exists() {
                fs::write(&blob_path, payload_bytes).map_err(|e| {
                    HivemindError::system("blob_write_failed", e.to_string(), origin)
                        .with_context("path", blob_path.display().to_string())
                })?;
            }
    
            let byte_size = u64::try_from(payload_bytes.len()).unwrap_or(u64::MAX);
    
            Ok(NativeBlobRef {
                digest,
                byte_size,
                media_type: media_type.to_string(),
                blob_path: blob_path.to_string_lossy().to_string(),
                payload: if matches!(mode, NativePayloadCaptureMode::FullPayload) {
                    Some(payload.to_string())
                } else {
                    None
                },
            })
        }

        #[allow(clippy::too_many_arguments, clippy::too_many_lines)]
        fn append_native_invocation_events(
            &self,
            flow: &TaskFlow,
            task_id: Uuid,
            attempt_id: Uuid,
            correlation: &CorrelationIds,
            adapter_name: &str,
            invocation: &NativeInvocationTrace,
            origin: &'static str,
        ) -> Result<()> {
            let native_correlation = Self::native_event_correlation(flow, task_id, attempt_id);
            let capture_mode = Self::native_capture_mode_for_event(invocation.capture_mode);
    
            self.append_event(
                Event::new(
                    EventPayload::AgentInvocationStarted {
                        native_correlation: native_correlation.clone(),
                        invocation_id: invocation.invocation_id.clone(),
                        adapter_name: adapter_name.to_string(),
                        provider: invocation.provider.clone(),
                        model: invocation.model.clone(),
                        runtime_version: invocation.runtime_version.clone(),
                        capture_mode,
                    },
                    correlation.clone(),
                ),
                origin,
            )?;
    
            let mut saw_tool_failure = false;
    
            for turn in &invocation.turns {
                self.append_event(
                    Event::new(
                        EventPayload::AgentTurnStarted {
                            native_correlation: native_correlation.clone(),
                            invocation_id: invocation.invocation_id.clone(),
                            turn_index: turn.turn_index,
                            from_state: turn.from_state.clone(),
                        },
                        correlation.clone(),
                    ),
                    origin,
                )?;
    
                let request = self.persist_native_blob(
                    "application/json",
                    &turn.model_request,
                    invocation.capture_mode,
                    origin,
                )?;
                self.append_event(
                    Event::new(
                        EventPayload::ModelRequestPrepared {
                            native_correlation: native_correlation.clone(),
                            invocation_id: invocation.invocation_id.clone(),
                            turn_index: turn.turn_index,
                            request,
                        },
                        correlation.clone(),
                    ),
                    origin,
                )?;
    
                let response = self.persist_native_blob(
                    "text/plain; charset=utf-8",
                    &turn.model_response,
                    invocation.capture_mode,
                    origin,
                )?;
                self.append_event(
                    Event::new(
                        EventPayload::ModelResponseReceived {
                            native_correlation: native_correlation.clone(),
                            invocation_id: invocation.invocation_id.clone(),
                            turn_index: turn.turn_index,
                            response,
                        },
                        correlation.clone(),
                    ),
                    origin,
                )?;
    
                for tool_call in &turn.tool_calls {
                    let request = self.persist_native_blob(
                        "text/plain; charset=utf-8",
                        &tool_call.request,
                        invocation.capture_mode,
                        origin,
                    )?;
                    self.append_event(
                        Event::new(
                            EventPayload::ToolCallRequested {
                                native_correlation: native_correlation.clone(),
                                task_id: Some(task_id),
                                invocation_id: invocation.invocation_id.clone(),
                                turn_index: turn.turn_index,
                                call_id: tool_call.call_id.clone(),
                                tool_name: tool_call.tool_name.clone(),
                                request,
                                policy_tags: tool_call.policy_tags.clone(),
                            },
                            correlation.clone(),
                        ),
                        origin,
                    )?;
    
                    self.append_event(
                        Event::new(
                            EventPayload::ToolCallStarted {
                                native_correlation: native_correlation.clone(),
                                task_id: Some(task_id),
                                invocation_id: invocation.invocation_id.clone(),
                                turn_index: turn.turn_index,
                                call_id: tool_call.call_id.clone(),
                                tool_name: tool_call.tool_name.clone(),
                                policy_tags: tool_call.policy_tags.clone(),
                            },
                            correlation.clone(),
                        ),
                        origin,
                    )?;
    
                    if let Some(failure) = &tool_call.failure {
                        saw_tool_failure = true;
                        self.append_event(
                            Event::new(
                                EventPayload::ToolCallFailed {
                                    native_correlation: native_correlation.clone(),
                                    task_id: Some(task_id),
                                    invocation_id: invocation.invocation_id.clone(),
                                    turn_index: turn.turn_index,
                                    call_id: tool_call.call_id.clone(),
                                    tool_name: tool_call.tool_name.clone(),
                                    code: failure.code.clone(),
                                    message: failure.message.clone(),
                                    recoverable: failure.recoverable,
                                    policy_tags: tool_call.policy_tags.clone(),
                                },
                                correlation.clone(),
                            ),
                            origin,
                        )?;
                    } else if let Some(response_payload) = tool_call.response.as_deref() {
                        let response = self.persist_native_blob(
                            "text/plain; charset=utf-8",
                            response_payload,
                            invocation.capture_mode,
                            origin,
                        )?;
                        self.append_event(
                            Event::new(
                                EventPayload::ToolCallCompleted {
                                    native_correlation: native_correlation.clone(),
                                    task_id: Some(task_id),
                                    invocation_id: invocation.invocation_id.clone(),
                                    turn_index: turn.turn_index,
                                    call_id: tool_call.call_id.clone(),
                                    tool_name: tool_call.tool_name.clone(),
                                    response,
                                    policy_tags: tool_call.policy_tags.clone(),
                                },
                                correlation.clone(),
                            ),
                            origin,
                        )?;
                        self.append_graph_query_event_for_native_tool_call(
                            flow,
                            task_id,
                            attempt_id,
                            &tool_call.tool_name,
                            response_payload,
                            correlation.clone(),
                            origin,
                        )?;
                    }
                }
    
                self.append_event(
                    Event::new(
                        EventPayload::AgentTurnCompleted {
                            native_correlation: native_correlation.clone(),
                            invocation_id: invocation.invocation_id.clone(),
                            turn_index: turn.turn_index,
                            to_state: turn.to_state.clone(),
                            summary: turn.turn_summary.clone(),
                        },
                        correlation.clone(),
                    ),
                    origin,
                )?;
            }
    
            for attempt in &invocation.transport.attempts {
                let category = if attempt.rate_limited {
                    "rate_limit"
                } else if attempt.code.starts_with("native_stream_") {
                    "transport_stream"
                } else {
                    "transport"
                };
                self.append_event(
                    Event::new(
                        EventPayload::RuntimeErrorClassified {
                            attempt_id,
                            adapter_name: adapter_name.to_string(),
                            code: attempt.code.clone(),
                            category: category.to_string(),
                            message: attempt.message.clone(),
                            recoverable: attempt.retryable,
                            retryable: attempt.retryable,
                            rate_limited: attempt.rate_limited,
                        },
                        correlation.clone(),
                    ),
                    origin,
                )?;
    
                if let Some(backoff_ms) = attempt.backoff_ms {
                    self.append_event(
                        Event::new(
                            EventPayload::RuntimeRecoveryScheduled {
                                attempt_id,
                                from_adapter: format!("{adapter_name}:{}", attempt.transport),
                                to_adapter: format!("{adapter_name}:{}", attempt.transport),
                                strategy: "native_transport_retry".to_string(),
                                reason: format!(
                                    "turn={} code={} retryable={}",
                                    attempt.turn_index, attempt.code, attempt.retryable
                                ),
                                backoff_ms,
                            },
                            correlation.clone(),
                        ),
                        origin,
                    )?;
                }
            }
    
            for fallback in &invocation.transport.fallback_activations {
                self.append_event(
                    Event::new(
                        EventPayload::RuntimeRecoveryScheduled {
                            attempt_id,
                            from_adapter: format!("{adapter_name}:{}", fallback.from_transport),
                            to_adapter: format!("{adapter_name}:{}", fallback.to_transport),
                            strategy: "native_transport_fallback".to_string(),
                            reason: format!("turn={} reason={}", fallback.turn_index, fallback.reason),
                            backoff_ms: 0,
                        },
                        correlation.clone(),
                    ),
                    origin,
                )?;
            }
    
            if let Some(runtime_state) = invocation.runtime_state.as_ref() {
                self.append_event(
                    Event::new(
                        EventPayload::RuntimeRecoveryScheduled {
                            attempt_id,
                            from_adapter: format!("{adapter_name}:runtime_state:init"),
                            to_adapter: format!("{adapter_name}:runtime_state:ready"),
                            strategy: "native_runtime_state_bootstrap".to_string(),
                            reason: format!(
                                "db_path={} busy_timeout_ms={} log_batch_size={} retention_days={}",
                                runtime_state.db_path,
                                runtime_state.busy_timeout_ms,
                                runtime_state.log_batch_size,
                                runtime_state.log_retention_days
                            ),
                            backoff_ms: 0,
                        },
                        correlation.clone(),
                    ),
                    origin,
                )?;
            }
    
            for transition in &invocation.readiness_transitions {
                self.append_event(
                    Event::new(
                        EventPayload::RuntimeRecoveryScheduled {
                            attempt_id,
                            from_adapter: format!(
                                "{adapter_name}:{}:{}",
                                transition.component, transition.from_state
                            ),
                            to_adapter: format!(
                                "{adapter_name}:{}:{}",
                                transition.component, transition.to_state
                            ),
                            strategy: "native_component_readiness".to_string(),
                            reason: format!(
                                "token={} ts_ms={} reason={}",
                                transition.token, transition.timestamp_ms, transition.reason
                            ),
                            backoff_ms: 0,
                        },
                        correlation.clone(),
                    ),
                    origin,
                )?;
    
                if transition.to_state == "failed" {
                    self.append_event(
                        Event::new(
                            EventPayload::RuntimeErrorClassified {
                                attempt_id,
                                adapter_name: adapter_name.to_string(),
                                code: "native_component_not_ready".to_string(),
                                category: "runtime_setup".to_string(),
                                message: format!(
                                    "Native component '{}' failed readiness transition: {}",
                                    transition.component, transition.reason
                                ),
                                recoverable: false,
                                retryable: false,
                                rate_limited: false,
                            },
                            correlation.clone(),
                        ),
                        origin,
                    )?;
                }
            }
    
            let success = invocation.failure.is_none() && !saw_tool_failure;
            let (error_code, error_message, recoverable) = invocation.failure.as_ref().map_or_else(
                || {
                    if saw_tool_failure {
                        (
                            Some("native_tool_call_failed".to_string()),
                            Some("One or more native tool calls failed".to_string()),
                            Some(false),
                        )
                    } else {
                        (None, None, None)
                    }
                },
                |failure| {
                    (
                        Some(failure.code.clone()),
                        Some(failure.message.clone()),
                        Some(failure.recoverable),
                    )
                },
            );
    
            self.append_event(
                Event::new(
                    EventPayload::AgentInvocationCompleted {
                        native_correlation,
                        invocation_id: invocation.invocation_id.clone(),
                        total_turns: u32::try_from(invocation.turns.len()).unwrap_or(u32::MAX),
                        final_state: invocation.final_state.clone(),
                        success,
                        final_summary: invocation.final_summary.clone(),
                        error_code,
                        error_message,
                        recoverable,
                    },
                    correlation.clone(),
                ),
                origin,
            )?;
    
            Ok(())
        }

}
